### PR TITLE
Adding initial key for mnm678

### PR DESCRIPTION
**Pull request by mnm678**
Signed-off-by: Marina Moore <mnm678@gmail.com>

### CODE REVIEW

**Review by asraa — APPROVED** [review]
VERIFIED KEY 14470876

**Comment by annebdh** [comment]
LGTM!

**Comment by puerco** [comment]
> VERIFIED KEY 14470876


/lgtm

**Comment by nadgowdas** [comment]
LGTM!

**Comment by znewman01** [comment]
LGTM
VERIFIED KEY 14470876

**Comment by garrying** [comment]
LGTM!

**Comment by jchester** [comment]
LGTM

**Comment by jimangel** [comment]
🍍 
LGTM

**Comment by ethan-lowman-dd** [comment]
`VERIFIED KEY 14470876`

LGTM

**Comment by magnologan** [comment]
LGTM

**Comment by zjs** [comment]
```
Outputting key verification and OpenSSL commands...

VERIFIED KEY 14470876

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14470876/14470876_device_cert.pem) ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem -pubkey -noout
```

```
~/src/root-signing (VERIFY)$ openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14470876/14470876_device_cert.pem) ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem
ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem: OK
```

```
~/src/root-signing (VERIFY)$ openssl x509 -in ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem -pubkey -noout
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEXsz3SZXFb8jMV42j6pJlyjbjR8K
N3Bwocexq6LMIb5qsWKOQvLN16NUefLc4HswOoumRsVVaajSpQS6fobkRw==
-----END PUBLIC KEY-----
```

LGTM

**Comment by tiziano88** [comment]
LGTM
Slowpoke

**Comment by xopham** [comment]
LGTM

**Comment by hojoungjang** [comment]
LGTM!
`VERIFIED KEY 14470876`
`ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem: OK`
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEXsz3SZXFb8jMV42j6pJlyjbjR8K
N3Bwocexq6LMIb5qsWKOQvLN16NUefLc4HswOoumRsVVaajSpQS6fobkRw==
-----END PUBLIC KEY-----
```

**Comment by tclasen** [comment]
LGTM!

**Pull request merged**
