### PR TITLE
DO NOT MERGE: Enable tuf-on-ci

### PR DESCRIPTION
**Pull request by jku**
**Do not merge**, this is informative only at this point.

These are the workflow changes I propose we include in the initial signing event PR, I'm making this a draft PR already so these can be reviewed separately and in advance of the actual signing event (#929).

Contents
* Remove legacy workflows
* Enable tuf-on-ci workflows (except publishing to production: let's do that after manual testing)
* Add a note in README: Let's fixup the README after the event

### CODE REVIEW

**Comment by jku** [comment]
I'm filing an issue to remove some of the expected checks and will fix this PR so it does not remove the workflow linting

**Comment by jku** [comment]
@kommendorkapten please have a look at some point

**Review by kommendorkapten — DISMISSED** [review]
LGTM

**Comment by jku** [comment]
rebased on main to keep this up-to-date.

**Comment by jku** [comment]
closing as I've merged to PR 1323

**Pull request closed without merging**
