### PR TITLE
Signing root and targets for dlorenc

### PR DESCRIPTION
**Pull request by dlorenc**
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by asraa** [comment]
Dope, 1 valid sig added to root.json and targets.json in staged metadata:

```
STAGED METADATA

Outputting metadata verification at /home/asraa/git/root-signing/ceremony/2022-05-09...

Verifying rekor.json...
	Contains 0/1 valid signatures
	rekor version 2, expires 2022/11/10

Verifying root.json...
	Contains 1/3 valid signatures
	root version 3, expires 2022/11/10

Verifying targets.json...
	Contains 1/3 valid signatures
	targets version 3, expires 2022/11/10

Verifying revocation.json...
	Contains 0/1 valid signatures
	revocation version 1, expires 2022/11/10
```

**Review by asraa — APPROVED** [review]

**Comment by Hayden-IO** [comment]
@asraa , `./scripts/verify.sh 207`, correct?

```
STAGED METADATA

Outputting metadata verification at /Users/hblauzvern/development/root-signing/ceremony/2022-05-09...

Verifying root.json...
	Contains 1/3 valid signatures
	root version 3, expires 2022/11/10

Verifying revocation.json...
	Contains 0/1 valid signatures
	revocation version 1, expires 2022/11/10

Verifying targets.json...
	Contains 1/3 valid signatures
	targets version 3, expires 2022/11/10

Verifying rekor.json...
	Contains 0/1 valid signatures
	rekor version 2, expires 2022/11/10
```

**Review by Hayden-IO — APPROVED** [review]

**Comment by asraa** [comment]
> @asraa , ./scripts/verify.sh 207, correct?

yep!

**Comment by bobcallaway** [comment]
```sh
Verifying targets.json...
	Contains 1/3 valid signatures
	targets version 3, expires 2022/11/10

Verifying revocation.json...
	Contains 0/1 valid signatures
	revocation version 1, expires 2022/11/10

Verifying rekor.json...
	Contains 0/1 valid signatures
	rekor version 2, expires 2022/11/10

Verifying root.json...
	Contains 1/3 valid signatures
	root version 3, expires 2022/11/10
```

**Pull request merged**
