### PR TITLE
Staging v4: Fix lack of end date for ct log

### PR DESCRIPTION
**Pull request by Hayden-IO**

### CODE REVIEW

**Comment by Hayden-IO** [comment]
@loosebazooka Can you test against this?

**Comment by Hayden-IO** [comment]
Confirmed that v3 updates to v4 cleanly with Cosign

**Comment by loosebazooka** [comment]
Hrmm. Yeah I'll have to do it a bit manually if it's not published. Lemme see if I can tonight. Otherwise I'll do it in the morning

**Comment by loosebazooka** [comment]
Seems to work, at least the "current" part which was broken before.

**Review by kommendorkapten — APPROVED** [review]

**Review by loosebazooka — APPROVED** [review]

**Pull request merged**
