### PR TITLE
Updated registry.npmjs.org delegation.

### PR DESCRIPTION
**Pull request by kommendorkapten**
* Updated expiration date
* Bumbed version to 2
* Signed the delegation

# What to review

* Make sure that the key have not changed for the delegation.
* The target (`keys.json`) is not modified
* Expected version bumps and expiration dates

### CODE REVIEW

**Comment by kommendorkapten** [comment]
Diffs against previous version:

```shell
kommendorkapten@m1m14:~/git/root-signing % git rev-parse --abbrev-ref HEAD
test-v8-add-delegation-npmjs
kommendorkapten@m1m14:~/git/root-signing % diff -u repository/repository/registry.npmjs.org.json repository/staged/registry.npmjs.org.json
--- repository/repository/registry.npmjs.org.json	2023-04-14 13:34:23
+++ repository/staged/registry.npmjs.org.json	2023-09-19 13:47:56
@@ -2,8 +2,8 @@
 	"signed": {
 		"_type": "targets",
 		"spec_version": "1.0",
-		"version": 1,
-		"expires": "2023-10-04T13:26:23Z",
+		"version": 2,
+		"expires": "2024-03-19T12:46:19Z",
 		"targets": {
 			"registry.npmjs.org/keys.json": {
 				"length": 1017,
\ No newline at end of file
@@ -17,7 +17,7 @@
 	"signatures": [
 		{
 			"keyid": "a89d235ee2f298d757438c7473b11b0b7b42ff1a45f1dfaac4c014183d6f8c45",
-			"sig": "304402201acf213d8e3dea0a5f0c1757e4409a02661bcfab3278419307994ead07c36cb4022029986ed2241c630c4e45bf97e043c23220df7612e3718f921fe8a99c7515ad30"
+			"sig": "3045022100a4757c589b21d6efcf2a258489a8c0eccfa89c536284e9367e091bfaf03c8ae9022075cb450b269ef522c03ccb92bdbc68a9069588f6fe608aca07918c5a51e918ef"
 		}
 	]
 }
\ No newline at end of file
kommendorkapten@m1m14:~/git/root-signing % diff -u repository/repository/targets.json repository/staged/targets.json
--- repository/repository/targets.json	2023-04-14 13:34:23
+++ repository/staged/targets.json	2023-09-19 13:46:19
@@ -2,8 +2,8 @@
 	"signed": {
 		"_type": "targets",
 		"spec_version": "1.0",
-		"version": 7,
-		"expires": "2023-10-04T13:26:23Z",
+		"version": 8,
+		"expires": "2024-03-19T12:46:19Z",
 		"targets": {
 			"artifact.pub": {
 				"length": 177,
\ No newline at end of file
@@ -141,20 +141,24 @@
 	},
 	"signatures": [
 		{
-			"keyid": "2e61cd0cbf4a8f45809bda9f7f78c0d33ad11842ff94ae340873e2664dc843de",
-			"sig": "3045022100eeb820ad0b0aabb0f6bf68159d7a9cbd24d1c4633f14317f9944fcb3bb2e1ff802207f92fb20b84df6bcf0c3c2f39fa089238bbee9ff12490c555b694421a45e8d5d"
+			"keyid": "ff51e17fcf253119b7033f6f57512631da4a0969442afcf9fc8b141c7f2be99c",
+			"sig": ""
 		},
 		{
 			"keyid": "25a0eb450fd3ee2bd79218c963dce3f1cc6118badf251bf149f0bd07d5cabe99",
-			"sig": "304502202984e536e9442c9f5a14700195b481fb0b3255e4572734700c5ff527b1135f88022100be2f4947b34a02e391417c96ffab8643476164fc44fa258bfe0133ab49858f29"
+			"sig": ""
 		},
 		{
 			"keyid": "f5312f542c21273d9485a49394386c4575804770667f2ddb59b3bf0669fddd2f",
-			"sig": "3045022100d757e9268801bb1eb4f883abd570dae52a3201c622b4e7e5a30a8b42f3e2f54b02206663b846a8d13d95497d651334dbb754587a14c274fadd91ca796733bc467b95"
+			"sig": ""
 		},
 		{
 			"keyid": "7f7513b25429a64473e10ce3ad2f3da372bbdd14b65d07bbaf547e7c8bbbe62b",
-			"sig": "3045022054d7fb7d70a80f8f4021f090307ada7a196a32f4794954baf405475b38e68d45022100d85fde60eecb2003e4eb329e1b68f22d33dbe11a2293155dad88209250b25b2c"
+			"sig": ""
+		},
+		{
+			"keyid": "2e61cd0cbf4a8f45809bda9f7f78c0d33ad11842ff94ae340873e2664dc843de",
+			"sig": ""
 		}
 	]
 }
\ No newline at end of file
diff -u repository/repository/targets/registry.npmjs.org/7a8ec9678ad824cdccaa7a6dc0961caf8f8df61bc7274189122c123446248426.keys.json repository/staged/targets/registry.npmjs.org/keys.json
kommendorkapten@m1m14:~/git/root-signing %
```

**Review by Hayden-IO — APPROVED** [review]
Do we have any scripts I should be running to verify this?

**Comment by kommendorkapten** [comment]
@haydentherapper Yes, forgot to paste the command:

```shell
$ make verify
$ ./verify repository --repository=./repository --staged
STAGED METADATA

Outputting metadata verification at ./repository...

Verifying targets.json...
	Contains 0/3 valid signatures from the current staged metadata
	targets version 8, expires 2024/03/19

Verifying root.json...
	Contains 0/3 valid signatures from the current staged metadata
	Contains 0/3 valid signatures from the previous root
	root version 8, expires 2024/03/19

Verifying registry.npmjs.org.json...
	Success! Signatures valid and threshold achieved
	registry.npmjs.org version 2, expires 2024/03/19
```

**Comment by Hayden-IO** [comment]
Confirmed:

```
$ ./verify repository --repository=./repository --staged
STAGED METADATA

Outputting metadata verification at ./repository...

Verifying root.json...
	Contains 0/3 valid signatures from the current staged metadata
	Contains 0/3 valid signatures from the previous root
	root version 8, expires 2024/03/19

Verifying registry.npmjs.org.json...
	Success! Signatures valid and threshold achieved
	registry.npmjs.org version 2, expires 2024/03/19

Verifying targets.json...
	Contains 0/3 valid signatures from the current staged metadata
	targets version 8, expires 2024/03/19
```

**Pull request merged**
