### PR TITLE
ci: fix token perms issue in snapshot/timestamp

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Fix errors from https://github.com/sigstore/root-signing/actions/runs/3227710181/jobs/5282862486#step:6:24

1. Adds the single-quote around `provider` to fix the audience request URL error:
2. Fix the job that intends to publish an issue when workflows fail. The script looked for `TOKEN` env var, rather than the defined `GITHUB_TOKEN`.
3. Fixes a resolution in a key variable `{{ inputs.snapshot_key }}`

cc @jku

### CODE REVIEW

**Review by Hayden-IO — DISMISSED** [review]

**Comment by jku** [comment]
wait, there is also a bug in the key variables:
compare these two:

          echo "REPO=$(pwd)/${{ inputs.repo }}" >> $GITHUB_ENV
          echo "SNAPSHOT_KEY={{ inputs.snapshot_key }}" >> $GITHUB_ENV

the latter is missing a $

**Comment by jku** [comment]
Can I ask for a short explanation in the commit message?

There's now two separate fixes here, and if my comment is correct, a third one is needed (in this PR or another). Would be nice to see them explained in the text even if they're fairly trivial.

**Comment by Hayden-IO** [comment]
FYI, this was brought up in the GA meeting, I noted this should not be an issue and will be fixed shortly. We'll want to manually sync preprod and prod once a successful snapshot has occurred to avoid any issues imo.

**Comment by asraa** [comment]
> We'll want to manually sync preprod and prod once a successful snapshot has occurred to avoid any issues imo.

Plus this one! https://github.com/sigstore/root-signing/issues/460

**Comment by asraa** [comment]
Updated the description and the env var resolution!

**Review by Hayden-IO — APPROVED** [review]

**Pull request merged**
