### PR TITLE
Adding initial key for lukehinds

### PR DESCRIPTION
**Pull request by lukehinds**
Signed-off-by: Luke Hinds <lhinds@redhat.com>

### CODE REVIEW

**Review by asraa — APPROVED** [review]
VERIFIED KEY 14454335

**Comment by puerco** [comment]
> VERIFIED KEY 14454335

/lgtm

**Comment by znewman01** [comment]
LGTM
VERIFIED KEY 14454335

**Comment by ethan-lowman-dd** [comment]
`VERIFIED KEY 14454335`

LGTM

**Comment by garrying** [comment]
LGTM!

**Review by mbestavros — APPROVED** [review]
LGTM!

**Comment by jchester** [comment]
LGTM

**Comment by mmalone** [comment]
LGTM

**Comment by zjs** [comment]
```
Outputting key verification and OpenSSL commands...

VERIFIED KEY 14454335

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14454335/14454335_device_cert.pem) ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem -pubkey -noout
```

```
~/src/root-signing (VERIFY)$ openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14454335/14454335_device_cert.pem) ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem
ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem: OK
```

```
~/src/root-signing (VERIFY)$ openssl x509 -in ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem -pubkey -noout
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEpxqs2DXcFwum2z+jOhoz3udR1Piw
IXuAW5vTJCkh7pNnL9z9hAV2xbsNwO2BXt85TB7kjCteAkheWb/FEvOtxw==
-----END PUBLIC KEY-----
```

LGTM

**Comment by denisse-dev** [comment]
LGTM!

`VERIFIED KEY 14454335`

```bash
openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14454335/14454335_device_cert.pem) ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem
ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem: OK
```

```bash
openssl x509 -in ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem -pubkey -noout

-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEpxqs2DXcFwum2z+jOhoz3udR1Piw
IXuAW5vTJCkh7pNnL9z9hAV2xbsNwO2BXt85TB7kjCteAkheWb/FEvOtxw==
-----END PUBLIC KEY-----
```

**Comment by hojoungjang** [comment]
LGTM!
`VERIFIED KEY 14454335`
`ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem: OK`
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEpxqs2DXcFwum2z+jOhoz3udR1Piw
IXuAW5vTJCkh7pNnL9z9hAV2xbsNwO2BXt85TB7kjCteAkheWb/FEvOtxw==
-----END PUBLIC KEY-----
```

**Comment by tclasen** [comment]
LGTM!

**Pull request merged**
