### PR TITLE
Signing delegations

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

#### Summary

* Fortunately snapshotting and timestamping reminded me I forgot to run `scripts/step-3.sh`

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Review by trishankatdatadog — APPROVED** [review]
```
$ CEREMONY_DATE=2021-10-19 GITHUB_USER=trishankatdatadog ./scripts/verify.sh 49

Outputting key verification and OpenSSL commands...

VERIFIED KEY 13078778

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-19/keys/13078778/13078778_device_cert.pem) ceremony/2021-10-19/keys/13078778/13078778_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-10-19/keys/13078778/13078778_key_cert.pem -pubkey -noout

VERIFIED KEY 14454335

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-19/keys/14454335/14454335_device_cert.pem) ceremony/2021-10-19/keys/14454335/14454335_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-10-19/keys/14454335/14454335_key_cert.pem -pubkey -noout

VERIFIED KEY 14470876

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-19/keys/14470876/14470876_device_cert.pem) ceremony/2021-10-19/keys/14470876/14470876_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-10-19/keys/14470876/14470876_key_cert.pem -pubkey -noout

VERIFIED KEY 15938765

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-19/keys/15938765/15938765_device_cert.pem) ceremony/2021-10-19/keys/15938765/15938765_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-10-19/keys/15938765/15938765_key_cert.pem -pubkey -noout

VERIFIED KEY 15938791

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-19/keys/15938791/15938791_device_cert.pem) ceremony/2021-10-19/keys/15938791/15938791_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-10-19/keys/15938791/15938791_key_cert.pem -pubkey -noout

Outputting metadata verification...

Verifying root...
	Success! Signatures valid and threshold achieved

Verifying snapshot...
	Contains 0/1 valid signatures

Verifying targets...
	Success! Signatures valid and threshold achieved

Verifying timestamp...
	Contains 0/1 valid signatures

Validating completed metadata and retrieving targets...
Client successfully initialized, downloading targets...
error updating client: tuf: failed to decode timestamp.json: tuf: valid signatures did not meet threshold
```

**Comment by cpanato** [comment]
```
$ CEREMONY_DATE=2021-10-19 GITHUB_USER=cpanato ./scripts/verify.sh 49 

Outputting key verification and OpenSSL commands...

VERIFIED KEY 13078778

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-19/keys/13078778/13078778_device_cert.pem) ceremony/2021-10-19/keys/13078778/13078778_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-10-19/keys/13078778/13078778_key_cert.pem -pubkey -noout

VERIFIED KEY 14454335

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-19/keys/14454335/14454335_device_cert.pem) ceremony/2021-10-19/keys/14454335/14454335_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-10-19/keys/14454335/14454335_key_cert.pem -pubkey -noout

VERIFIED KEY 14470876

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-19/keys/14470876/14470876_device_cert.pem) ceremony/2021-10-19/keys/14470876/14470876_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-10-19/keys/14470876/14470876_key_cert.pem -pubkey -noout

VERIFIED KEY 15938765

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-19/keys/15938765/15938765_device_cert.pem) ceremony/2021-10-19/keys/15938765/15938765_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-10-19/keys/15938765/15938765_key_cert.pem -pubkey -noout

VERIFIED KEY 15938791

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-19/keys/15938791/15938791_device_cert.pem) ceremony/2021-10-19/keys/15938791/15938791_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-10-19/keys/15938791/15938791_key_cert.pem -pubkey -noout

Outputting metadata verification...

Verifying snapshot...
        Contains 0/1 valid signatures

Verifying targets...
        Success! Signatures valid and threshold achieved

Verifying timestamp...
        Contains 0/1 valid signatures

Verifying root...
        Success! Signatures valid and threshold achieved
```

**Review by SantiagoTorres — APPROVED** [review]
Took me a little bit to understand the change to sign.go, but LGTM

**Comment by asraa** [comment]
Yeah :/ a lot of the unconventional stuff is really just around those placeholder sigs we had for offline key signing so we don't get merge conflicts

**Pull request merged**
