### PR TITLE
Add new TUF keyids to keyholder list

### PR DESCRIPTION
**Pull request by joshuagl**
Update the keyholders list in the README to include the TUF keyids for the new key formats introduced in the v5 ceremony.

We continue to list the old TUF keyids for now as they help explain the continuity from v4 to v5 (it's the same key materials, just different key formats and keyids).

Signed-off-by: Joshua Lock <jlock@vmware.com>

### CODE REVIEW

**Review by asraa — APPROVED** [review]
I like marking them as v5+! If we decide to publish the v5 in a separate repository, then this is perfect.

**Comment by joshuagl** [comment]
> I like marking them as v5+! If we decide to publish the v5 in a separate repository, then this is perfect.

Should we hold on merging this until that decision is made?

**Comment by asraa** [comment]
SGTM! I have a feeling we'll drop the split and update to v5 anyway.

**Review by asraa — APPROVED** [review]
@joshuagl I think merging this as is is good -- it's good to document and keep history of the new and previous key IDs

**Pull request merged**
