### PR TITLE
sign-delegations for asraa

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

#### Summary

To verify, run
```
REPO=$(pwd)/ceremony/2022-07-12 ./scripts/verify.sh 319
```

You should see in the STAGED METADATA section, that the delegations (staging, rekor, revocation) are fully signed, and that root and targets are too.

### CODE REVIEW

**Comment by elfotografo007** [comment]
Switched to branch 'VERIFY'
+ '[' -d /Users/elfotografo007/git/root-signing/ceremony/2022-07-12/keys ']'
+ ./verify keys --root piv-attestation-ca.pem --key-directory /Users/elfotografo007/git/root-signing/ceremony/2022-07-12/keys

Outputting key verification and OpenSSL commands...

VERIFIED KEY WITH SERIAL NUMBER 13078778
	TUF key id: 2f64fb5eac0cf94dd39bb45308b98920055e9a0d8e012a7220787834c60aef97

VERIFIED KEY WITH SERIAL NUMBER 14470876
	TUF key id: eaf22372f417dd618a46f6c627dbc276e9fd30a004fc94f9be946e73f8bd090b

VERIFIED KEY WITH SERIAL NUMBER 15938765
	TUF key id: f40f32044071a9365505da3d1e3be6561f6f22d0e60cf51df783999f6c3429cb

VERIFIED KEY WITH SERIAL NUMBER 15938791
	TUF key id: f505595165a177a41750a8e864ed1719b1edfccd5a426fd2c0ffda33ce7ff209

VERIFIED KEY WITH SERIAL NUMBER 18158855
	TUF key id: 75e867ab10e121fdef32094af634707f43ddd79c6bab8ad6c5ab9f03f4ea8c90

# To manually verify the chain for any key ID

	export SERIAL_NUMBER=${SERIAL_NUMBER}
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_device_cert.pem) ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_key_cert.pem

# Manually extract the public key for any key ID and match with published

	export SERIAL_NUMBER=${SERIAL_NUMBER}
	openssl x509 -in ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_key_cert.pem -pubkey -noout
	cat ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_pubkey.pem
+ '[' -f /Users/elfotografo007/git/root-signing/ceremony/2022-07-12/staged/root.json ']'
+ ./verify repository --repository /Users/elfotografo007/git/root-signing/ceremony/2022-07-12 --staged
STAGED METADATA

Outputting metadata verification at /Users/elfotografo007/git/root-signing/ceremony/2022-07-12...

Verifying rekor.json...
	Success! Signatures valid and threshold achieved
	rekor version 3, expires 2023/01/12

Verifying root.json...
	Success! Signatures valid and threshold achieved
	root version 4, expires 2023/01/12

Verifying staging.json...
	Success! Signatures valid and threshold achieved
	staging version 2, expires 2022/11/10

Verifying targets.json...
	Success! Signatures valid and threshold achieved
	targets version 4, expires 2023/01/12

Verifying revocation.json...
	Success! Signatures valid and threshold achieved
	revocation version 1, expires 2023/01/12
+ '[' -f /Users/elfotografo007/git/root-signing/ceremony/2022-07-12/repository/1.root.json ']'
+ ./verify repository --repository /Users/elfotografo007/git/root-signing/ceremony/2022-07-12 --root /Users/elfotografo007/git/root-signing/ceremony/2022-07-12/repository/1.root.json

VERIFYING TUF CLIENT UPDATE

Client successfully initialized, updating and downloading targets...
Client updated to...
	root.json version 3, expires 2022/11/10
	timestamp.json version 37, expires 2022/07/22
	snapshot.json version 37, expires 2022/07/29
	targets.json version 3, expires 2022/11/10

Retrieved target fulcio_v1.crt.pem...
-----BEGIN CERTIFICATE-----
MIIB9zCCAXygAwIBAgIUALZNAPFdxHPwjeDloDwyYChAO/4wCgYIKoZIzj0EAwMw
KjEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MREwDwYDVQQDEwhzaWdzdG9yZTAeFw0y
MTEwMDcxMzU2NTlaFw0zMTEwMDUxMzU2NThaMCoxFTATBgNVBAoTDHNpZ3N0b3Jl
LmRldjERMA8GA1UEAxMIc2lnc3RvcmUwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAT7
XeFT4rb3PQGwS4IajtLk3/OlnpgangaBclYpsYBr5i+4ynB07ceb3LP0OIOZdxex
X69c5iVuyJRQ+Hz05yi+UF3uBWAlHpiS5sh0+H2GHE7SXrk1EC5m1Tr19L9gg92j
YzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRY
wB5fkUWlZql6zJChkyLQKsXF+jAfBgNVHSMEGDAWgBRYwB5fkUWlZql6zJChkyLQ
KsXF+jAKBggqhkjOPQQDAwNpADBmAjEAj1nHeXZp+13NWBNa+EDsDP8G1WWg1tCM
WP/WHPqpaVo0jhsweNFZgSs0eE7wYI4qAjEA2WB9ot98sIkoF3vZYdd3/VtWB5b9
TNMea7Ix/stJ5TfcLLeABLE4BNJOsQ4vnBHJ
-----END CERTIFICATE-----

Retrieved target rekor.0.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2G2Y+2tabdTV5BcGiBIx0a9fAFwr
kBbmLSGtks4L3qX6yYY0zufBnhC8Ur/iy55GhWP/9A/bY2LhC30M9+RYtw==
-----END PUBLIC KEY-----

Retrieved target rekor.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2G2Y+2tabdTV5BcGiBIx0a9fAFwr
kBbmLSGtks4L3qX6yYY0zufBnhC8Ur/iy55GhWP/9A/bY2LhC30M9+RYtw==
-----END PUBLIC KEY-----

Retrieved target artifact.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhyQCx0E9wQWSFI9ULGwy3BuRklnt
IqozONbbdbqz11hlRJy9c7SG+hdcFl9jE9uE/dwtuwU2MqU9T/cN0YkWww==
-----END PUBLIC KEY-----

Retrieved target ctfe.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbfwR+RJudXscgRBRpKX1XFDy3Pyu
dDxz/SfnRi1fT8ekpfBd2O1uoz7jr3Z8nKzxA69EUQ+eFCFI3zeubPWU7w==
-----END PUBLIC KEY-----

Retrieved target fulcio.crt.pem...
-----BEGIN CERTIFICATE-----
MIIB+DCCAX6gAwIBAgITNVkDZoCiofPDsy7dfm6geLbuhzAKBggqhkjOPQQDAzAq
MRUwEwYDVQQKEwxzaWdzdG9yZS5kZXYxETAPBgNVBAMTCHNpZ3N0b3JlMB4XDTIx
MDMwNzAzMjAyOVoXDTMxMDIyMzAzMjAyOVowKjEVMBMGA1UEChMMc2lnc3RvcmUu
ZGV2MREwDwYDVQQDEwhzaWdzdG9yZTB2MBAGByqGSM49AgEGBSuBBAAiA2IABLSy
A7Ii5k+pNO8ZEWY0ylemWDowOkNa3kL+GZE5Z5GWehL9/A9bRNA3RbrsZ5i0Jcas
taRL7Sp5fp/jD5dxqc/UdTVnlvS16an+2Yfswe/QuLolRUCrcOE2+2iA5+tzd6Nm
MGQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
FMjFHQBBmiQpMlEk6w2uSu1KBtPsMB8GA1UdIwQYMBaAFMjFHQBBmiQpMlEk6w2u
Su1KBtPsMAoGCCqGSM49BAMDA2gAMGUCMH8liWJfMui6vXXBhjDgY4MwslmN/TJx
Ve/83WrFomwmNf056y1X48F9c4m3a3ozXAIxAKjRay5/aj/jsKKGIkmQatjI8uup
Hr/+CxFvaJWmpYqNkLDGRU+9orzh5hI2RrcuaQ==
-----END CERTIFICATE-----

LGTM

**Comment by kommendorkapten** [comment]
```
kommendorkapten@m1m14:~/git/root-signing % GITHUB_USER=kommendorkapten REPO=$(pwd)/ceremony/2022-07-12 ./scripts/verify.sh 319
+ '[' -z kommendorkapten ']'
+ '[' -z /Users/kommendorkapten/git/root-signing/ceremony/2022-07-12 ']'
+ git checkout main
Switched to branch 'main'
+ git status
On branch main
nothing to commit, working tree clean
+ git remote -v
origin	git@github.com:kommendorkapten/root-signing.git (fetch)
origin	git@github.com:kommendorkapten/root-signing.git (push)
upstream	git@github.com:sigstore/root-signing.git (fetch)
upstream	git@github.com:sigstore/root-signing.git (push)
+ git remote rm upstream
+ git remote add upstream git@github.com:sigstore/root-signing.git
+ git remote rm origin
+ git remote add origin git@github.com:kommendorkapten/root-signing.git
+ git remote -v
origin	git@github.com:kommendorkapten/root-signing.git (fetch)
origin	git@github.com:kommendorkapten/root-signing.git (push)
upstream	git@github.com:sigstore/root-signing.git (fetch)
upstream	git@github.com:sigstore/root-signing.git (push)
+ go build -o verify ./cmd/verify
+ '[' -f piv-attestation-ca.pem ']'
+ [[ ! -z 319 ]]
+ echo 'Pull Request: 319'
Pull Request: 319
+ git branch -D VERIFY
Deleted branch VERIFY (was b09e85a).
+ git fetch upstream pull/319/head:VERIFY
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 56 (delta 28), reused 28 (delta 12), pack-reused 1
Unpacking objects: 100% (56/56), 14.26 KiB | 356.00 KiB/s, done.
From github.com:sigstore/root-signing
 * [new ref]         refs/pull/319/head -> VERIFY
+ git checkout VERIFY
Switched to branch 'VERIFY'
+ '[' -d /Users/kommendorkapten/git/root-signing/ceremony/2022-07-12/keys ']'
+ ./verify keys --root piv-attestation-ca.pem --key-directory /Users/kommendorkapten/git/root-signing/ceremony/2022-07-12/keys

Outputting key verification and OpenSSL commands...

VERIFIED KEY WITH SERIAL NUMBER 13078778
	TUF key id: 2f64fb5eac0cf94dd39bb45308b98920055e9a0d8e012a7220787834c60aef97

VERIFIED KEY WITH SERIAL NUMBER 14470876
	TUF key id: eaf22372f417dd618a46f6c627dbc276e9fd30a004fc94f9be946e73f8bd090b

VERIFIED KEY WITH SERIAL NUMBER 15938765
	TUF key id: f40f32044071a9365505da3d1e3be6561f6f22d0e60cf51df783999f6c3429cb

VERIFIED KEY WITH SERIAL NUMBER 15938791
	TUF key id: f505595165a177a41750a8e864ed1719b1edfccd5a426fd2c0ffda33ce7ff209

VERIFIED KEY WITH SERIAL NUMBER 18158855
	TUF key id: 75e867ab10e121fdef32094af634707f43ddd79c6bab8ad6c5ab9f03f4ea8c90

# To manually verify the chain for any key ID

	export SERIAL_NUMBER=${SERIAL_NUMBER}
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_device_cert.pem) ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_key_cert.pem

# Manually extract the public key for any key ID and match with published

	export SERIAL_NUMBER=${SERIAL_NUMBER}
	openssl x509 -in ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_key_cert.pem -pubkey -noout
	cat ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_pubkey.pem
+ '[' -f /Users/kommendorkapten/git/root-signing/ceremony/2022-07-12/staged/root.json ']'
+ ./verify repository --repository /Users/kommendorkapten/git/root-signing/ceremony/2022-07-12 --staged
STAGED METADATA

Outputting metadata verification at /Users/kommendorkapten/git/root-signing/ceremony/2022-07-12...

Verifying targets.json...
	Success! Signatures valid and threshold achieved
	targets version 4, expires 2023/01/12

Verifying root.json...
	Success! Signatures valid and threshold achieved
	root version 4, expires 2023/01/12

Verifying staging.json...
	Success! Signatures valid and threshold achieved
	staging version 2, expires 2022/11/10

Verifying rekor.json...
	Success! Signatures valid and threshold achieved
	rekor version 3, expires 2023/01/12

Verifying revocation.json...
	Success! Signatures valid and threshold achieved
	revocation version 1, expires 2023/01/12
+ '[' -f /Users/kommendorkapten/git/root-signing/ceremony/2022-07-12/repository/1.root.json ']'
+ ./verify repository --repository /Users/kommendorkapten/git/root-signing/ceremony/2022-07-12 --root /Users/kommendorkapten/git/root-signing/ceremony/2022-07-12/repository/1.root.json

VERIFYING TUF CLIENT UPDATE

Client successfully initialized, updating and downloading targets...
Client updated to...
	root.json version 3, expires 2022/11/10
	timestamp.json version 37, expires 2022/07/22
	snapshot.json version 37, expires 2022/07/29
	targets.json version 3, expires 2022/11/10

Retrieved target artifact.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhyQCx0E9wQWSFI9ULGwy3BuRklnt
IqozONbbdbqz11hlRJy9c7SG+hdcFl9jE9uE/dwtuwU2MqU9T/cN0YkWww==
-----END PUBLIC KEY-----

Retrieved target ctfe.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbfwR+RJudXscgRBRpKX1XFDy3Pyu
dDxz/SfnRi1fT8ekpfBd2O1uoz7jr3Z8nKzxA69EUQ+eFCFI3zeubPWU7w==
-----END PUBLIC KEY-----

Retrieved target fulcio.crt.pem...
-----BEGIN CERTIFICATE-----
MIIB+DCCAX6gAwIBAgITNVkDZoCiofPDsy7dfm6geLbuhzAKBggqhkjOPQQDAzAq
MRUwEwYDVQQKEwxzaWdzdG9yZS5kZXYxETAPBgNVBAMTCHNpZ3N0b3JlMB4XDTIx
MDMwNzAzMjAyOVoXDTMxMDIyMzAzMjAyOVowKjEVMBMGA1UEChMMc2lnc3RvcmUu
ZGV2MREwDwYDVQQDEwhzaWdzdG9yZTB2MBAGByqGSM49AgEGBSuBBAAiA2IABLSy
A7Ii5k+pNO8ZEWY0ylemWDowOkNa3kL+GZE5Z5GWehL9/A9bRNA3RbrsZ5i0Jcas
taRL7Sp5fp/jD5dxqc/UdTVnlvS16an+2Yfswe/QuLolRUCrcOE2+2iA5+tzd6Nm
MGQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
FMjFHQBBmiQpMlEk6w2uSu1KBtPsMB8GA1UdIwQYMBaAFMjFHQBBmiQpMlEk6w2u
Su1KBtPsMAoGCCqGSM49BAMDA2gAMGUCMH8liWJfMui6vXXBhjDgY4MwslmN/TJx
Ve/83WrFomwmNf056y1X48F9c4m3a3ozXAIxAKjRay5/aj/jsKKGIkmQatjI8uup
Hr/+CxFvaJWmpYqNkLDGRU+9orzh5hI2RrcuaQ==
-----END CERTIFICATE-----

Retrieved target fulcio_v1.crt.pem...
-----BEGIN CERTIFICATE-----
MIIB9zCCAXygAwIBAgIUALZNAPFdxHPwjeDloDwyYChAO/4wCgYIKoZIzj0EAwMw
KjEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MREwDwYDVQQDEwhzaWdzdG9yZTAeFw0y
MTEwMDcxMzU2NTlaFw0zMTEwMDUxMzU2NThaMCoxFTATBgNVBAoTDHNpZ3N0b3Jl
LmRldjERMA8GA1UEAxMIc2lnc3RvcmUwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAT7
XeFT4rb3PQGwS4IajtLk3/OlnpgangaBclYpsYBr5i+4ynB07ceb3LP0OIOZdxex
X69c5iVuyJRQ+Hz05yi+UF3uBWAlHpiS5sh0+H2GHE7SXrk1EC5m1Tr19L9gg92j
YzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRY
wB5fkUWlZql6zJChkyLQKsXF+jAfBgNVHSMEGDAWgBRYwB5fkUWlZql6zJChkyLQ
KsXF+jAKBggqhkjOPQQDAwNpADBmAjEAj1nHeXZp+13NWBNa+EDsDP8G1WWg1tCM
WP/WHPqpaVo0jhsweNFZgSs0eE7wYI4qAjEA2WB9ot98sIkoF3vZYdd3/VtWB5b9
TNMea7Ix/stJ5TfcLLeABLE4BNJOsQ4vnBHJ
-----END CERTIFICATE-----

Retrieved target rekor.0.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2G2Y+2tabdTV5BcGiBIx0a9fAFwr
kBbmLSGtks4L3qX6yYY0zufBnhC8Ur/iy55GhWP/9A/bY2LhC30M9+RYtw==
-----END PUBLIC KEY-----

Retrieved target rekor.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2G2Y+2tabdTV5BcGiBIx0a9fAFwr
kBbmLSGtks4L3qX6yYY0zufBnhC8Ur/iy55GhWP/9A/bY2LhC30M9+RYtw==
-----END PUBLIC KEY-----
```

Looks good!

**Review by bobcallaway — APPROVED** [review]
```sh
+ ./verify repository --repository /Users/bcallaway/git/sigstore/root-signing/ceremony/2022-07-12 --staged
STAGED METADATA

Outputting metadata verification at /Users/bcallaway/git/sigstore/root-signing/ceremony/2022-07-12...

Verifying rekor.json...
	Success! Signatures valid and threshold achieved
	rekor version 3, expires 2023/01/12

Verifying targets.json...
	Success! Signatures valid and threshold achieved
	targets version 4, expires 2023/01/12

Verifying revocation.json...
	Success! Signatures valid and threshold achieved
	revocation version 1, expires 2023/01/12

Verifying root.json...
	Success! Signatures valid and threshold achieved
	root version 4, expires 2023/01/12

Verifying staging.json...
	Success! Signatures valid and threshold achieved
	staging version 2, expires 2022/11/10
+ '[' -f /Users/bcallaway/git/sigstore/root-signing/ceremony/2022-07-12/repository/1.root.json ']'
+ ./verify repository --repository /Users/bcallaway/git/sigstore/root-signing/ceremony/2022-07-12 --root /Users/bcallaway/git/sigstore/root-signing/ceremony/2022-07-12/repository/1.root.json

VERIFYING TUF CLIENT UPDATE

Client successfully initialized, updating and downloading targets...
Client updated to...
	root.json version 3, expires 2022/11/10
	timestamp.json version 37, expires 2022/07/22
	snapshot.json version 37, expires 2022/07/29
	targets.json version 3, expires 2022/11/10
```

**Review by joshuagl — COMMENTED** [review]
```
Verifying staging.json...
	Success! Signatures valid and threshold achieved
	staging version 2, expires 2022/11/10

Verifying rekor.json...
	Success! Signatures valid and threshold achieved
	rekor version 3, expires 2023/01/12

Verifying targets.json...
	Success! Signatures valid and threshold achieved
	targets version 4, expires 2023/01/12

Verifying root.json...
	Success! Signatures valid and threshold achieved
	root version 4, expires 2023/01/12

Verifying revocation.json...
	Success! Signatures valid and threshold achieved
	revocation version 1, expires 2023/01/12
```

**Review by joshuagl — APPROVED** [review]

**Pull request merged**
