### PR TITLE
sign-root-targets for bobcallaway - 2nd attempt

### PR DESCRIPTION
**Pull request by bobcallaway**
Signed-off-by: Bob Callaway <bcallaway@google.com>

### CODE REVIEW

**Review by asraa — APPROVED** [review]
Thanks! The sigs check out
```
STAGED METADATA

Outputting metadata verification at /home/asraa/git/root-signing/ceremony/2022-10-03...

Verifying targets.json...
	Contains 1/3 valid signatures from the current staged metadata
	targets version 5, expires 2023/04/03

Verifying root.json...
	Contains 1/3 valid signatures from the current staged metadata
	Contains 1/3 valid signatures from the previous root
	root version 5, expires 2023/04/03
+ '[' -f /home/asraa/git/root-signing/ceremony/2022-10-03/repository/1.root.json ']'
```

**Review by joshuagl — APPROVED** [review]
```
VERIFIED KEY WITH SERIAL NUMBER 18158855
TUF key ids:
	75e867ab10e121fdef32094af634707f43ddd79c6bab8ad6c5ab9f03f4ea8c90 [deprecated]
	2e61cd0cbf4a8f45809bda9f7f78c0d33ad11842ff94ae340873e2664dc843de [new]
```

```
Outputting metadata verification at /Users/jlock/Projects/root-signing-ceremony/ceremony/2022-10-03...

Verifying targets.json...
	Contains 1/3 valid signatures from the current staged metadata
	targets version 5, expires 2023/04/03

Verifying root.json...
	Contains 1/3 valid signatures from the current staged metadata
	Contains 1/3 valid signatures from the previous root
	root version 5, expires 2023/04/03
```

**Comment by cpanato** [comment]
```
+ '[' -z cpanato ']'
+ '[' -z /Users/cpanato/code/src/github.com/sigstore/root-signing/ceremony/2022-10-03 ']'
+ git checkout main
Switched to branch 'main'
+ git status
On branch main
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	log.txt

nothing added to commit but untracked files present (use "git add" to track)
+ git remote -v
origin	git@github.com:cpanato/root-signing.git (fetch)
origin	git@github.com:cpanato/root-signing.git (push)
upstream	git@github.com:sigstore/root-signing.git (fetch)
upstream	git@github.com:sigstore/root-signing.git (push)
+ git remote rm upstream
+ git remote add upstream git@github.com:sigstore/root-signing.git
+ git remote rm origin
+ git remote add origin git@github.com:cpanato/root-signing.git
+ git remote -v
origin	git@github.com:cpanato/root-signing.git (fetch)
origin	git@github.com:cpanato/root-signing.git (push)
upstream	git@github.com:sigstore/root-signing.git (fetch)
upstream	git@github.com:sigstore/root-signing.git (push)
+ go build -o verify ./cmd/verify
+ '[' -f piv-attestation-ca.pem ']'
+ [[ -n 437 ]]
+ echo 'Pull Request: 437'
Pull Request: 437
+ git branch -D VERIFY
Deleted branch VERIFY (was 227f69e).
+ git fetch upstream pull/437/head:VERIFY
From github.com:sigstore/root-signing
 * [new ref]         refs/pull/437/head -> VERIFY
+ git checkout VERIFY
Switched to branch 'VERIFY'
+ '[' -d /Users/cpanato/code/src/github.com/sigstore/root-signing/ceremony/2022-10-03/keys ']'
+ ./verify keys --root piv-attestation-ca.pem --key-directory /Users/cpanato/code/src/github.com/sigstore/root-signing/ceremony/2022-10-03/keys

Outputting key verification and OpenSSL commands...

VERIFIED KEY WITH SERIAL NUMBER 13078778
TUF key ids: 
	2f64fb5eac0cf94dd39bb45308b98920055e9a0d8e012a7220787834c60aef97 [deprecated]
	ff51e17fcf253119b7033f6f57512631da4a0969442afcf9fc8b141c7f2be99c [new]

VERIFIED KEY WITH SERIAL NUMBER 14470876
TUF key ids: 
	eaf22372f417dd618a46f6c627dbc276e9fd30a004fc94f9be946e73f8bd090b [deprecated]
	25a0eb450fd3ee2bd79218c963dce3f1cc6118badf251bf149f0bd07d5cabe99 [new]

VERIFIED KEY WITH SERIAL NUMBER 15938765
TUF key ids: 
	f40f32044071a9365505da3d1e3be6561f6f22d0e60cf51df783999f6c3429cb [deprecated]
	f5312f542c21273d9485a49394386c4575804770667f2ddb59b3bf0669fddd2f [new]

VERIFIED KEY WITH SERIAL NUMBER 15938791
TUF key ids: 
	f505595165a177a41750a8e864ed1719b1edfccd5a426fd2c0ffda33ce7ff209 [deprecated]
	7f7513b25429a64473e10ce3ad2f3da372bbdd14b65d07bbaf547e7c8bbbe62b [new]

VERIFIED KEY WITH SERIAL NUMBER 18158855
TUF key ids: 
	75e867ab10e121fdef32094af634707f43ddd79c6bab8ad6c5ab9f03f4ea8c90 [deprecated]
	2e61cd0cbf4a8f45809bda9f7f78c0d33ad11842ff94ae340873e2664dc843de [new]

 To match pubkey values of the two TUF key IDs, perform the following command and verify a match:

	export NEW_ID=${NEW_ID}
	export DEPRECATED_ID=${DEPRECATED_ID}
	cat ceremony/2022-10-03/staged/root.json | jq --arg id "${NEW_ID}" -r '.signed.keys[$id].keyval.public' | openssl ec -pubin -inform PEM -text -noout
	cat ceremony/2022-10-03/repository/root.json | jq --arg id "${DEPRECATED_ID}" -r '.signed.keys[$id].keyval.public'

# To manually verify the chain for any key ID

	export SERIAL_NUMBER=${SERIAL_NUMBER}
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2022-10-03/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_device_cert.pem) ceremony/2022-10-03/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_key_cert.pem

# Manually extract the public key for any key ID and match with published

	export SERIAL_NUMBER=${SERIAL_NUMBER}
	openssl x509 -in ceremony/2022-10-03/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_key_cert.pem -pubkey -noout
	cat ceremony/2022-10-03/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_pubkey.pem
+ '[' -f /Users/cpanato/code/src/github.com/sigstore/root-signing/ceremony/2022-10-03/staged/root.json ']'
+ ./verify repository --repository /Users/cpanato/code/src/github.com/sigstore/root-signing/ceremony/2022-10-03 --staged
STAGED METADATA

Outputting metadata verification at /Users/cpanato/code/src/github.com/sigstore/root-signing/ceremony/2022-10-03...

Verifying root.json...
	Contains 1/3 valid signatures from the current staged metadata
	Contains 1/3 valid signatures from the previous root
	root version 5, expires 2023/04/03

Verifying targets.json...
	Contains 1/3 valid signatures from the current staged metadata
	targets version 5, expires 2023/04/03
+ '[' -f /Users/cpanato/code/src/github.com/sigstore/root-signing/ceremony/2022-10-03/repository/1.root.json ']'
+ ./verify repository --repository /Users/cpanato/code/src/github.com/sigstore/root-signing/ceremony/2022-10-03 --root /Users/cpanato/code/src/github.com/sigstore/root-signing/ceremony/2022-10-03/repository/1.root.json

VERIFYING TUF CLIENT UPDATE

Client successfully initialized, updating and downloading targets...
Client updated to...
	root.json version 4, expires 2023/01/12
	timestamp.json version 50, expires 2022/10/17
	snapshot.json version 50, expires 2022/10/24
	targets.json version 4, expires 2023/01/12

Retrieved target rekor.0.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2G2Y+2tabdTV5BcGiBIx0a9fAFwr
kBbmLSGtks4L3qX6yYY0zufBnhC8Ur/iy55GhWP/9A/bY2LhC30M9+RYtw==
-----END PUBLIC KEY-----

Retrieved target rekor.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2G2Y+2tabdTV5BcGiBIx0a9fAFwr
kBbmLSGtks4L3qX6yYY0zufBnhC8Ur/iy55GhWP/9A/bY2LhC30M9+RYtw==
-----END PUBLIC KEY-----

Retrieved target artifact.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhyQCx0E9wQWSFI9ULGwy3BuRklnt
IqozONbbdbqz11hlRJy9c7SG+hdcFl9jE9uE/dwtuwU2MqU9T/cN0YkWww==
-----END PUBLIC KEY-----

Retrieved target ctfe.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbfwR+RJudXscgRBRpKX1XFDy3Pyu
dDxz/SfnRi1fT8ekpfBd2O1uoz7jr3Z8nKzxA69EUQ+eFCFI3zeubPWU7w==
-----END PUBLIC KEY-----

Retrieved target fulcio.crt.pem...
-----BEGIN CERTIFICATE-----
MIIB+DCCAX6gAwIBAgITNVkDZoCiofPDsy7dfm6geLbuhzAKBggqhkjOPQQDAzAq
MRUwEwYDVQQKEwxzaWdzdG9yZS5kZXYxETAPBgNVBAMTCHNpZ3N0b3JlMB4XDTIx
MDMwNzAzMjAyOVoXDTMxMDIyMzAzMjAyOVowKjEVMBMGA1UEChMMc2lnc3RvcmUu
ZGV2MREwDwYDVQQDEwhzaWdzdG9yZTB2MBAGByqGSM49AgEGBSuBBAAiA2IABLSy
A7Ii5k+pNO8ZEWY0ylemWDowOkNa3kL+GZE5Z5GWehL9/A9bRNA3RbrsZ5i0Jcas
taRL7Sp5fp/jD5dxqc/UdTVnlvS16an+2Yfswe/QuLolRUCrcOE2+2iA5+tzd6Nm
MGQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
FMjFHQBBmiQpMlEk6w2uSu1KBtPsMB8GA1UdIwQYMBaAFMjFHQBBmiQpMlEk6w2u
Su1KBtPsMAoGCCqGSM49BAMDA2gAMGUCMH8liWJfMui6vXXBhjDgY4MwslmN/TJx
Ve/83WrFomwmNf056y1X48F9c4m3a3ozXAIxAKjRay5/aj/jsKKGIkmQatjI8uup
Hr/+CxFvaJWmpYqNkLDGRU+9orzh5hI2RrcuaQ==
-----END CERTIFICATE-----

Retrieved target fulcio_intermediate_v1.crt.pem...
-----BEGIN CERTIFICATE-----
MIICGjCCAaGgAwIBAgIUALnViVfnU0brJasmRkHrn/UnfaQwCgYIKoZIzj0EAwMw
KjEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MREwDwYDVQQDEwhzaWdzdG9yZTAeFw0y
MjA0MTMyMDA2MTVaFw0zMTEwMDUxMzU2NThaMDcxFTATBgNVBAoTDHNpZ3N0b3Jl
LmRldjEeMBwGA1UEAxMVc2lnc3RvcmUtaW50ZXJtZWRpYXRlMHYwEAYHKoZIzj0C
AQYFK4EEACIDYgAE8RVS/ysH+NOvuDZyPIZtilgUF9NlarYpAd9HP1vBBH1U5CV7
7LSS7s0ZiH4nE7Hv7ptS6LvvR/STk798LVgMzLlJ4HeIfF3tHSaexLcYpSASr1kS
0N/RgBJz/9jWCiXno3sweTAOBgNVHQ8BAf8EBAMCAQYwEwYDVR0lBAwwCgYIKwYB
BQUHAwMwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQU39Ppz1YkEZb5qNjp
KFWixi4YZD8wHwYDVR0jBBgwFoAUWMAeX5FFpWapesyQoZMi0CrFxfowCgYIKoZI
zj0EAwMDZwAwZAIwPCsQK4DYiZYDPIaDi5HFKnfxXx6ASSVmERfsynYBiX2X6SJR
nZU84/9DZdnFvvxmAjBOt6QpBlc4J/0DxvkTCqpclvziL6BCCPnjdlIB3Pu3BxsP
mygUY7Ii2zbdCdliiow=
-----END CERTIFICATE-----

Retrieved target fulcio_v1.crt.pem...
-----BEGIN CERTIFICATE-----
MIIB9zCCAXygAwIBAgIUALZNAPFdxHPwjeDloDwyYChAO/4wCgYIKoZIzj0EAwMw
KjEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MREwDwYDVQQDEwhzaWdzdG9yZTAeFw0y
MTEwMDcxMzU2NTlaFw0zMTEwMDUxMzU2NThaMCoxFTATBgNVBAoTDHNpZ3N0b3Jl
LmRldjERMA8GA1UEAxMIc2lnc3RvcmUwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAT7
XeFT4rb3PQGwS4IajtLk3/OlnpgangaBclYpsYBr5i+4ynB07ceb3LP0OIOZdxex
X69c5iVuyJRQ+Hz05yi+UF3uBWAlHpiS5sh0+H2GHE7SXrk1EC5m1Tr19L9gg92j
YzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRY
wB5fkUWlZql6zJChkyLQKsXF+jAfBgNVHSMEGDAWgBRYwB5fkUWlZql6zJChkyLQ
KsXF+jAKBggqhkjOPQQDAwNpADBmAjEAj1nHeXZp+13NWBNa+EDsDP8G1WWg1tCM
WP/WHPqpaVo0jhsweNFZgSs0eE7wYI4qAjEA2WB9ot98sIkoF3vZYdd3/VtWB5b9
TNMea7Ix/stJ5TfcLLeABLE4BNJOsQ4vnBHJ
-----END CERTIFICATE-----

```

**Review by kommendorkapten — APPROVED** [review]
Verify command runs as expected.

Signatures and keys are as expected for `root.json` and `targets.json`.

**Comment by elfotografo007** [comment]
+ '[' -z elfotografo007 ']'
+ '[' -z /Users/elfotografo007/git/root-signing/ceremony/2022-10-03 ']'
+ git checkout main
Switched to branch 'main'
+ git status
On branch main
nothing to commit, working tree clean
+ git remote -v
origin	git@github.com:elfotografo007/root-signing.git (fetch)
origin	git@github.com:elfotografo007/root-signing.git (push)
upstream	git@github.com:sigstore/root-signing.git (fetch)
upstream	git@github.com:sigstore/root-signing.git (push)
+ git remote rm upstream
+ git remote add upstream git@github.com:sigstore/root-signing.git
+ git remote rm origin
+ git remote add origin git@github.com:elfotografo007/root-signing.git
+ git remote -v
origin	git@github.com:elfotografo007/root-signing.git (fetch)
origin	git@github.com:elfotografo007/root-signing.git (push)
upstream	git@github.com:sigstore/root-signing.git (fetch)
upstream	git@github.com:sigstore/root-signing.git (push)
+ go build -o verify ./cmd/verify
+ '[' -f piv-attestation-ca.pem ']'
+ [[ -n 437 ]]
+ echo 'Pull Request: 437'
Pull Request: 437
+ git branch -D VERIFY
Deleted branch VERIFY (was d955e46).
+ git fetch upstream pull/437/head:VERIFY
remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 7 (delta 5), reused 7 (delta 5), pack-reused 0
Unpacking objects: 100% (7/7), 803 bytes | 100.00 KiB/s, done.
From github.com:sigstore/root-signing
 * [new ref]         refs/pull/437/head -> VERIFY
+ git checkout VERIFY
Switched to branch 'VERIFY'
+ '[' -d /Users/elfotografo007/git/root-signing/ceremony/2022-10-03/keys ']'
+ ./verify keys --root piv-attestation-ca.pem --key-directory /Users/elfotografo007/git/root-signing/ceremony/2022-10-03/keys

Outputting key verification and OpenSSL commands...

VERIFIED KEY WITH SERIAL NUMBER 13078778
TUF key ids: 
	2f64fb5eac0cf94dd39bb45308b98920055e9a0d8e012a7220787834c60aef97 [deprecated]
	ff51e17fcf253119b7033f6f57512631da4a0969442afcf9fc8b141c7f2be99c [new]

VERIFIED KEY WITH SERIAL NUMBER 14470876
TUF key ids: 
	eaf22372f417dd618a46f6c627dbc276e9fd30a004fc94f9be946e73f8bd090b [deprecated]
	25a0eb450fd3ee2bd79218c963dce3f1cc6118badf251bf149f0bd07d5cabe99 [new]

VERIFIED KEY WITH SERIAL NUMBER 15938765
TUF key ids: 
	f40f32044071a9365505da3d1e3be6561f6f22d0e60cf51df783999f6c3429cb [deprecated]
	f5312f542c21273d9485a49394386c4575804770667f2ddb59b3bf0669fddd2f [new]

VERIFIED KEY WITH SERIAL NUMBER 15938791
TUF key ids: 
	f505595165a177a41750a8e864ed1719b1edfccd5a426fd2c0ffda33ce7ff209 [deprecated]
	7f7513b25429a64473e10ce3ad2f3da372bbdd14b65d07bbaf547e7c8bbbe62b [new]

VERIFIED KEY WITH SERIAL NUMBER 18158855
TUF key ids: 
	75e867ab10e121fdef32094af634707f43ddd79c6bab8ad6c5ab9f03f4ea8c90 [deprecated]
	2e61cd0cbf4a8f45809bda9f7f78c0d33ad11842ff94ae340873e2664dc843de [new]

 To match pubkey values of the two TUF key IDs, perform the following command and verify a match:

	export NEW_ID=${NEW_ID}
	export DEPRECATED_ID=${DEPRECATED_ID}
	cat ceremony/2022-10-03/staged/root.json | jq --arg id "${NEW_ID}" -r '.signed.keys[$id].keyval.public' | openssl ec -pubin -inform PEM -text -noout
	cat ceremony/2022-10-03/repository/root.json | jq --arg id "${DEPRECATED_ID}" -r '.signed.keys[$id].keyval.public'

# To manually verify the chain for any key ID

	export SERIAL_NUMBER=${SERIAL_NUMBER}
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2022-10-03/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_device_cert.pem) ceremony/2022-10-03/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_key_cert.pem

# Manually extract the public key for any key ID and match with published

	export SERIAL_NUMBER=${SERIAL_NUMBER}
	openssl x509 -in ceremony/2022-10-03/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_key_cert.pem -pubkey -noout
	cat ceremony/2022-10-03/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_pubkey.pem
+ '[' -f /Users/elfotografo007/git/root-signing/ceremony/2022-10-03/staged/root.json ']'
+ ./verify repository --repository /Users/elfotografo007/git/root-signing/ceremony/2022-10-03 --staged
STAGED METADATA

Outputting metadata verification at /Users/elfotografo007/git/root-signing/ceremony/2022-10-03...

Verifying targets.json...
	Contains 1/3 valid signatures from the current staged metadata
	targets version 5, expires 2023/04/03

Verifying root.json...
	Contains 1/3 valid signatures from the current staged metadata
	Contains 1/3 valid signatures from the previous root
	root version 5, expires 2023/04/03
+ '[' -f /Users/elfotografo007/git/root-signing/ceremony/2022-10-03/repository/1.root.json ']'
+ ./verify repository --repository /Users/elfotografo007/git/root-signing/ceremony/2022-10-03 --root /Users/elfotografo007/git/root-signing/ceremony/2022-10-03/repository/1.root.json

VERIFYING TUF CLIENT UPDATE

Client successfully initialized, updating and downloading targets...
Client updated to...
	timestamp.json version 50, expires 2022/10/17
	snapshot.json version 50, expires 2022/10/24
	targets.json version 4, expires 2023/01/12
	root.json version 4, expires 2023/01/12

Retrieved target artifact.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEhyQCx0E9wQWSFI9ULGwy3BuRklnt
IqozONbbdbqz11hlRJy9c7SG+hdcFl9jE9uE/dwtuwU2MqU9T/cN0YkWww==
-----END PUBLIC KEY-----

Retrieved target ctfe.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbfwR+RJudXscgRBRpKX1XFDy3Pyu
dDxz/SfnRi1fT8ekpfBd2O1uoz7jr3Z8nKzxA69EUQ+eFCFI3zeubPWU7w==
-----END PUBLIC KEY-----

Retrieved target fulcio.crt.pem...
-----BEGIN CERTIFICATE-----
MIIB+DCCAX6gAwIBAgITNVkDZoCiofPDsy7dfm6geLbuhzAKBggqhkjOPQQDAzAq
MRUwEwYDVQQKEwxzaWdzdG9yZS5kZXYxETAPBgNVBAMTCHNpZ3N0b3JlMB4XDTIx
MDMwNzAzMjAyOVoXDTMxMDIyMzAzMjAyOVowKjEVMBMGA1UEChMMc2lnc3RvcmUu
ZGV2MREwDwYDVQQDEwhzaWdzdG9yZTB2MBAGByqGSM49AgEGBSuBBAAiA2IABLSy
A7Ii5k+pNO8ZEWY0ylemWDowOkNa3kL+GZE5Z5GWehL9/A9bRNA3RbrsZ5i0Jcas
taRL7Sp5fp/jD5dxqc/UdTVnlvS16an+2Yfswe/QuLolRUCrcOE2+2iA5+tzd6Nm
MGQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
FMjFHQBBmiQpMlEk6w2uSu1KBtPsMB8GA1UdIwQYMBaAFMjFHQBBmiQpMlEk6w2u
Su1KBtPsMAoGCCqGSM49BAMDA2gAMGUCMH8liWJfMui6vXXBhjDgY4MwslmN/TJx
Ve/83WrFomwmNf056y1X48F9c4m3a3ozXAIxAKjRay5/aj/jsKKGIkmQatjI8uup
Hr/+CxFvaJWmpYqNkLDGRU+9orzh5hI2RrcuaQ==
-----END CERTIFICATE-----

Retrieved target fulcio_intermediate_v1.crt.pem...
-----BEGIN CERTIFICATE-----
MIICGjCCAaGgAwIBAgIUALnViVfnU0brJasmRkHrn/UnfaQwCgYIKoZIzj0EAwMw
KjEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MREwDwYDVQQDEwhzaWdzdG9yZTAeFw0y
MjA0MTMyMDA2MTVaFw0zMTEwMDUxMzU2NThaMDcxFTATBgNVBAoTDHNpZ3N0b3Jl
LmRldjEeMBwGA1UEAxMVc2lnc3RvcmUtaW50ZXJtZWRpYXRlMHYwEAYHKoZIzj0C
AQYFK4EEACIDYgAE8RVS/ysH+NOvuDZyPIZtilgUF9NlarYpAd9HP1vBBH1U5CV7
7LSS7s0ZiH4nE7Hv7ptS6LvvR/STk798LVgMzLlJ4HeIfF3tHSaexLcYpSASr1kS
0N/RgBJz/9jWCiXno3sweTAOBgNVHQ8BAf8EBAMCAQYwEwYDVR0lBAwwCgYIKwYB
BQUHAwMwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQU39Ppz1YkEZb5qNjp
KFWixi4YZD8wHwYDVR0jBBgwFoAUWMAeX5FFpWapesyQoZMi0CrFxfowCgYIKoZI
zj0EAwMDZwAwZAIwPCsQK4DYiZYDPIaDi5HFKnfxXx6ASSVmERfsynYBiX2X6SJR
nZU84/9DZdnFvvxmAjBOt6QpBlc4J/0DxvkTCqpclvziL6BCCPnjdlIB3Pu3BxsP
mygUY7Ii2zbdCdliiow=
-----END CERTIFICATE-----

Retrieved target fulcio_v1.crt.pem...
-----BEGIN CERTIFICATE-----
MIIB9zCCAXygAwIBAgIUALZNAPFdxHPwjeDloDwyYChAO/4wCgYIKoZIzj0EAwMw
KjEVMBMGA1UEChMMc2lnc3RvcmUuZGV2MREwDwYDVQQDEwhzaWdzdG9yZTAeFw0y
MTEwMDcxMzU2NTlaFw0zMTEwMDUxMzU2NThaMCoxFTATBgNVBAoTDHNpZ3N0b3Jl
LmRldjERMA8GA1UEAxMIc2lnc3RvcmUwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAT7
XeFT4rb3PQGwS4IajtLk3/OlnpgangaBclYpsYBr5i+4ynB07ceb3LP0OIOZdxex
X69c5iVuyJRQ+Hz05yi+UF3uBWAlHpiS5sh0+H2GHE7SXrk1EC5m1Tr19L9gg92j
YzBhMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBRY
wB5fkUWlZql6zJChkyLQKsXF+jAfBgNVHSMEGDAWgBRYwB5fkUWlZql6zJChkyLQ
KsXF+jAKBggqhkjOPQQDAwNpADBmAjEAj1nHeXZp+13NWBNa+EDsDP8G1WWg1tCM
WP/WHPqpaVo0jhsweNFZgSs0eE7wYI4qAjEA2WB9ot98sIkoF3vZYdd3/VtWB5b9
TNMea7Ix/stJ5TfcLLeABLE4BNJOsQ4vnBHJ
-----END CERTIFICATE-----

Retrieved target rekor.0.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2G2Y+2tabdTV5BcGiBIx0a9fAFwr
kBbmLSGtks4L3qX6yYY0zufBnhC8Ur/iy55GhWP/9A/bY2LhC30M9+RYtw==
-----END PUBLIC KEY-----

Retrieved target rekor.pub...
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE2G2Y+2tabdTV5BcGiBIx0a9fAFwr
kBbmLSGtks4L3qX6yYY0zufBnhC8Ur/iy55GhWP/9A/bY2LhC30M9+RYtw==
-----END PUBLIC KEY-----

**Review by flxw — APPROVED** [review]
[verification-output.log](https://github.com/sigstore/root-signing/files/9716281/verification-output.log)

**Pull request merged**
