### PR TITLE
Signing timestamp for lukehinds

### PR DESCRIPTION
**Pull request by lukehinds**
Signed-off-by: Luke Hinds <lhinds@redhat.com>

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
```
Outputting metadata verification...

Verifying root...
        Success! Signatures valid and threshold achieved

Verifying snapshot...
        Success! Signatures valid and threshold achieved

Verifying targets...
        Success! Signatures valid and threshold achieved

Verifying timestamp...
        Contains 1/3 valid signatures
        
```

**Comment by jchester** [comment]
```
$ pbpaste | shasum -a 512                                                               Fri Jun 18 11:49:58 2021
9103503c18f7da2098dce04892948ad240c1b9965048c4ab4da0c32248f3491652d91d76fe9022be2cf15a99e68b3a3ddd1034e5293c8aac86d0446c4354716d  -
```

`snapshot.json` LGTM.

**Review by asraa — APPROVED** [review]
Verifying root...
	Success! Signatures valid and threshold achieved

Verifying snapshot...
	Success! Signatures valid and threshold achieved

Verifying targets...
	Success! Signatures valid and threshold achieved

Verifying timestamp...
	Contains 1/3 valid signatures

**Comment by nishakm** [comment]
```
VERIFIED KEY 13078778

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/13078778/13078778_device_cert.pem) ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem -pubkey -noout

VERIFIED KEY 14454335

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14454335/14454335_device_cert.pem) ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem -pubkey -noout

VERIFIED KEY 14470876

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14470876/14470876_device_cert.pem) ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem -pubkey -noout

VERIFIED KEY 15938765

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938765/15938765_device_cert.pem) ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem -pubkey -noout

VERIFIED KEY 15938791

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938791/15938791_device_cert.pem) ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem -pubkey -noout

Outputting metadata verification...

Verifying targets...
	Success! Signatures valid and threshold achieved

Verifying timestamp...
	Contains 1/3 valid signatures

Verifying root...
	Success! Signatures valid and threshold achieved

Verifying snapshot...
	Success! Signatures valid and threshold achieved
```

**Comment by ethan-lowman-dd** [comment]
```
Outputting metadata verification...

Verifying snapshot...
        Success! Signatures valid and threshold achieved

Verifying targets...
        Success! Signatures valid and threshold achieved

Verifying timestamp...
        Contains 1/3 valid signatures

Verifying root...
        Success! Signatures valid and threshold achieved
```

LGTM

**Comment by xopham** [comment]
```
Outputting metadata verification...

Verifying root...
	Success! Signatures valid and threshold achieved

Verifying snapshot...
	Success! Signatures valid and threshold achieved

Verifying targets...
	Success! Signatures valid and threshold achieved

Verifying timestamp...
	Contains 1/3 valid signatures
```
LGTM

**Comment by puerco** [comment]
```
Outputting key verification and OpenSSL commands...

VERIFIED KEY 13078778
VERIFIED KEY 14454335
VERIFIED KEY 14470876
VERIFIED KEY 15938765
VERIFIED KEY 15938791

Outputting metadata verification...

Verifying root...
	Success! Signatures valid and threshold achieved
Verifying snapshot...
	Success! Signatures valid and threshold achieved
Verifying targets...
	Success! Signatures valid and threshold achieved
Verifying timestamp...
	Contains 1/3 valid signatures
```
/lgtm

**Comment by ethan-lowman-dd** [comment]
```
$ shasum -a 512 ceremony/2021-06-18/staged/snapshot.json                                                                                                                                                                     130 ↵
9103503c18f7da2098dce04892948ad240c1b9965048c4ab4da0c32248f3491652d91d76fe9022be2cf15a99e68b3a3ddd1034e5293c8aac86d0446c4354716d  ceremony/2021-06-18/staged/snapshot.json
```

**Comment by hojoungjang** [comment]
```
Verifying root...
        Success! Signatures valid and threshold achieved

Verifying snapshot...
        Success! Signatures valid and threshold achieved

Verifying targets...
        Success! Signatures valid and threshold achieved

Verifying timestamp...
        Contains 1/3 valid signatures
```
LGTM!

**Pull request merged**
