### PR TITLE
sign-root-targets for bobcallaway

### PR DESCRIPTION
**Pull request by bobcallaway**
Signed-off-by: Bob Callaway <bcallaway@google.com>

### CODE REVIEW

**Review by asraa — COMMENTED** [review]
While it functionally doesn't matter that you've added new placeholder signatures, I don't know why that happened and I'm taking a look!

**Review by flxw — APPROVED** [review]
I hereby confirm that verification worked successfully for me using the following command:
```
GITHUB_USER=flxw REPO=$(pwd)/ceremony/2022-10-03 ./scripts/verify.sh 434
```

**Review by codysoyland — APPROVED** [review]
verified

**Comment by asraa** [comment]
Thank you reviewers! Bob: now that the fix is merged to remove the excess changes (the extra empty signatures), could you run step-0 and step-2 again please?

**Pull request closed without merging**
