### PR TITLE
feat/add-delegation for registry.npmjs.org

### PR DESCRIPTION
**Pull request by kommendorkapten**
Test PR for add-delegation

This includes https://github.com/sigstore/root-signing/pull/748 to make the workflow for verifying POP succeed.

### CODE REVIEW

**Comment by kommendorkapten** [comment]
```shell
./scripts/dpop-verify.sh  750 registry.npmjs.org
+ set -u
+ MERGE_BASE=main
+ '[' 2 -gt 1 ']'
+ PR=750
+ DELEGATION=registry.npmjs.org
...
++ git rev-parse --abbrev-ref HEAD
+ BRANCH=VERIFY
++ git merge-base main VERIFY
+ FORK_POINT=77d5f6b30ad7fdd659ae22e570865ef90f9f9a2d
+ SIG_FILE=./repository/staged/77d5f6b30ad7fdd659ae22e570865ef90f9f9a2d.sig
+ '[' '!' -f ./repository/staged/77d5f6b30ad7fdd659ae22e570865ef90f9f9a2d.sig ']'
++ cat ./repository/staged/77d5f6b30ad7fdd659ae22e570865ef90f9f9a2d.sig
+ SIG=MEYCIQDxtL1ZQyLAfTJYUxh+2XKU2davfe3SQHhxI9rVMZInNQIhAK/C+stgXtYz0MahE5xDxya4yMHuz/3sC5YOgTuu5v9f
+ ./tuf key-pop-verify -role registry.npmjs.org -challenge registry.npmjs.org -nonce 77d5f6b30ad7fdd659ae22e570865ef90f9f9a2d -repository ./repository -sig MEYCIQDxtL1ZQyLAfTJYUxh+2XKU2davfe3SQHhxI9rVMZInNQIhAK/C+stgXtYz0MahE5xDxya4yMHuz/3sC5YOgTuu5v9f
Verifying using keyid 887361b214fd9c560d88329a8f256314f432000fd4a2bf6b30ac694e3825c678
Signature verified ok
```

**Comment by kommendorkapten** [comment]
```shell
./scripts/verify.sh 750
...
2 [ENTER]
...
STAGED METADATA

Outputting metadata verification at /Users/kommendorkapten/git/root-signing/repository...

Verifying root.json...
	Contains 0/3 valid signatures from the current staged metadata
	Contains 0/3 valid signatures from the previous root
	root version 7, expires 2023/09/23

Verifying registry.npmjs.org.json...
	Success! Signatures valid and threshold achieved
	registry.npmjs.org version 1, expires 2023/09/23

Verifying targets.json...
	Contains 0/3 valid signatures from the current staged metadata
	targets version 7, expires 2023/09/23
```

**Comment by kommendorkapten** [comment]
cc @asraa @haydentherapper

**Comment by asraa** [comment]
This worked!

```
2
STAGED METADATA

Outputting metadata verification at /home/asraa/git/root-signing/repository...

Verifying registry.npmjs.org.json...
	Success! Signatures valid and threshold achieved
	registry.npmjs.org version 1, expires 2023/09/23

Verifying root.json...
	Contains 0/3 valid signatures from the current staged metadata
	Contains 0/3 valid signatures from the previous root
	root version 7, expires 2023/09/23

Verifying targets.json...
	Contains 0/3 valid signatures from the current staged metadata
	targets version 7, expires 2023/09/23
```

**Comment by asraa** [comment]
Let's close this in prep for the ceremony this week!

**Pull request closed without merging**
