### PR TITLE
Update Snapshot and Timestamp

### PR DESCRIPTION
**Pull request by bobcallaway**
Sign snapshot and timestamp files

### CODE REVIEW

**Review by Hayden-IO — APPROVED** [review]
Even though it's three days, we should just kick it off

**Comment by asraa** [comment]
Should we just schedule for next week if the worry is about holidays?

**Comment by asraa** [comment]
OK I want to leave this open for testing auto-submission by a github actions bot.

**Review by asraa — APPROVED** [review]

**Comment by asraa** [comment]
I'd like to see if https://github.com/sigstore/root-signing/pull/556 will auto-merge.

**Comment by asraa** [comment]
oooh! It comes from sigstore-bot now. Thank you @cpanato !!

I'm looking up right now what perms are needed.
```
gh: Resource not accessible by personal access token (HTTP 403)
{"id":1202779468,"node_id":"PRR_kwDOFotDCM5HsPVM","user":{"login":"sigstore-bot","id":86837369,"node_id":"MDQ6VXNlcjg2ODM3MzY5","avatar_url":"https://avatars.githubusercontent.com/u/86837369?u=be1be7aa21ea7efee7dbbb5f8bf3fcd801e98010&v=4","gravatar_id":"","url":"https://api.github.com/users/sigstore-bot","html_url":"https://github.com/sigstore-bot","followers_url":"https://api.github.com/users/sigstore-bot/followers","following_url":"https://api.github.com/users/sigstore-bot/following{/other_user}","gists_url":"https://api.github.com/users/sigstore-bot/gists{/gist_id}","starred_url":"https://api.github.com/users/sigstore-bot/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/sigstore-bot/subscriptions","organizations_url":"https://api.github.com/users/sigstore-bot/orgs","repos_url":"https://api.github.com/users/sigstore-bot/repos","events_url":"https://api.github.com/users/sigstore-bot/events{/privacy}","received_events_url":"https://api.github.com/users/sigstore-bot/received_events","type":"User","site_admin":false},"body":"","state":"APPROVED","html_url":"https://github.com/sigstore/root-signing/pull/5[54](https://github.com/sigstore/root-signing/actions/runs/3603490372/jobs/6071750570#step:3:55)#pullrequestreview-1202779468","pull_request_url":"https://api.github.com/repos/sigstore/root-signing/pulls/554","author_association":"MEMBER","_links":{"html":{"href":"https://github.com/sigstore/root-signing/pull/554#pullrequestreview-1202779468"},"pull_request":{"href":"https://api.github.com/repos/sigstore/root-signing/pulls/554"}},"submitted_at":"2022-12-02T16:44:48Z","commit_id":"99f2427b871c9777f36a626dea82180d318c5a5a"}{"message":"Resource not accessible by personal access token","documentation_url":"https://docs.github.com/rest/reference/pulls#merge-a-pull-request"}
```

I wonder if we have to change some repository setting.

**Comment by cpanato** [comment]
we will need to add the bot in the repo, added manually for now but after the first successful run i will remove and add using the automation

**Pull request merged**
