### PR TITLE
sign-root-targets for mnm678

### PR DESCRIPTION
**Pull request by mnm678**
Signed-off-by: Marina Moore <mnm678@gmail.com>

### CODE REVIEW

**Review by joshuagl — APPROVED** [review]
keyids match for Marina and:
```
Outputting metadata verification at /Users/jlock/Projects/root-signing-ceremony/ceremony/2022-10-18...

Verifying targets.json...
	Contains 1/3 valid signatures from the current staged metadata
	targets version 5, expires 2023/04/18

Verifying root.json...
	Contains 1/3 valid signatures from the current staged metadata
	Contains 1/3 valid signatures from the previous root
	root version 5, expires 2023/04/18
```

**Review by asraa — APPROVED** [review]
LGTM!
```
STAGED METADATA

Outputting metadata verification at /home/asraa/git/root-signing/ceremony/2022-10-18/...

Verifying root.json...
	Contains 1/3 valid signatures from the current staged metadata
	Contains 1/3 valid signatures from the previous root
	root version 5, expires 2023/04/18

Verifying targets.json...
	Contains 1/3 valid signatures from the current staged metadata
	targets version 5, expires 2023/04/18
```

**Review by malancas — APPROVED** [review]
lgtm

```
STAGED METADATA

Outputting metadata verification at /Users/malancas/Code/sigstore/root-signing/ceremony/2022-10-18/...

Verifying root.json...
	Contains 1/3 valid signatures from the current staged metadata
	Contains 1/3 valid signatures from the previous root
	root version 5, expires 2023/04/18

Verifying targets.json...
	Contains 1/3 valid signatures from the current staged metadata
	targets version 5, expires 2023/04/18
+ '[' -f /Users/malancas/Code/sigstore/root-signing/ceremony/2022-10-18//repository/1.root.json ']'
+ ./verify repository --repository /Users/malancas/Code/sigstore/root-signing/ceremony/2022-10-18/ --root /Users/malancas/Code/sigstore/root-signing/ceremony/2022-10-18//repository/1.root.json
```

**Comment by pwelch** [comment]
```
STAGED METADATA

Outputting metadata verification at /Users/pwelch/code/github.com/sigstore/root-signing/ceremony/2022-10-18/...

Verifying root.json...
	Contains 1/3 valid signatures from the current staged metadata
	Contains 1/3 valid signatures from the previous root
	root version 5, expires 2023/04/18

Verifying targets.json...
	Contains 1/3 valid signatures from the current staged metadata
	targets version 5, expires 2023/04/18
```

```
VERIFIED KEY WITH SERIAL NUMBER 13078778
TUF key ids:
	2f64fb5eac0cf94dd39bb45308b98920055e9a0d8e012a7220787834c60aef97 [deprecated]
	ff51e17fcf253119b7033f6f57512631da4a0969442afcf9fc8b141c7f2be99c [new]

VERIFIED KEY WITH SERIAL NUMBER 14470876
TUF key ids:
	eaf22372f417dd618a46f6c627dbc276e9fd30a004fc94f9be946e73f8bd090b [deprecated]
	25a0eb450fd3ee2bd79218c963dce3f1cc6118badf251bf149f0bd07d5cabe99 [new]

VERIFIED KEY WITH SERIAL NUMBER 15938765
TUF key ids:
	f40f32044071a9365505da3d1e3be6561f6f22d0e60cf51df783999f6c3429cb [deprecated]
	f5312f542c21273d9485a49394386c4575804770667f2ddb59b3bf0669fddd2f [new]

VERIFIED KEY WITH SERIAL NUMBER 15938791
TUF key ids:
	f505595165a177a41750a8e864ed1719b1edfccd5a426fd2c0ffda33ce7ff209 [deprecated]
	7f7513b25429a64473e10ce3ad2f3da372bbdd14b65d07bbaf547e7c8bbbe62b [new]

VERIFIED KEY WITH SERIAL NUMBER 18158855
TUF key ids:
	75e867ab10e121fdef32094af634707f43ddd79c6bab8ad6c5ab9f03f4ea8c90 [deprecated]
	2e61cd0cbf4a8f45809bda9f7f78c0d33ad11842ff94ae340873e2664dc843de [new]
```

**Review by pwelch — APPROVED** [review]

**Comment by asraa** [comment]
Thank you both!

**Pull request merged**
