### PR TITLE
Signing targets for mnm678

### PR DESCRIPTION
**Pull request by mnm678**
Signed-off-by: Marina Moore <mnm678@gmail.com>

### CODE REVIEW

**Review by asraa — APPROVED** [review]
LGTM!


Verifying targets...
	Contains 1/3 valid signatures

Verifying timestamp...
	Contains 0/3 valid signatures

Verifying root...
	Contains 1/3 valid signatures

Verifying snapshot...
	Contains 0/3 valid signatures

**Comment by denisse-dev** [comment]
``` bash
Outputting key verification and OpenSSL commands...

VERIFIED KEY 13078778

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/13078778/13078778_device_cert.pem) ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem -pubkey -noout

VERIFIED KEY 14454335

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14454335/14454335_device_cert.pem) ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem -pubkey -noout

VERIFIED KEY 14470876

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14470876/14470876_device_cert.pem) ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem -pubkey -noout

VERIFIED KEY 15938765

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938765/15938765_device_cert.pem) ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem -pubkey -noout

VERIFIED KEY 15938791

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938791/15938791_device_cert.pem) ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem -pubkey -noout

Outputting metadata verification...

Verifying targets...
	Contains 1/3 valid signatures

Verifying timestamp...
	Contains 0/3 valid signatures

Verifying root...
	Contains 1/3 valid signatures

Verifying snapshot...
	Contains 0/3 valid signatures
```

**Comment by zjs** [comment]
```Outputting key verification and OpenSSL commands...

VERIFIED KEY 13078778

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/13078778/13078778_device_cert.pem) ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem -pubkey -noout

VERIFIED KEY 14454335

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14454335/14454335_device_cert.pem) ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem -pubkey -noout

VERIFIED KEY 14470876

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14470876/14470876_device_cert.pem) ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem -pubkey -noout

VERIFIED KEY 15938765

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938765/15938765_device_cert.pem) ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem -pubkey -noout

VERIFIED KEY 15938791

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938791/15938791_device_cert.pem) ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem -pubkey -noout

Outputting metadata verification...

Verifying root...
	Contains 1/3 valid signatures

Verifying snapshot...
	Contains 0/3 valid signatures

Verifying targets...
	Contains 1/3 valid signatures

Verifying timestamp...
	Contains 0/3 valid signatures
```

LGTM

**Comment by kkavitha** [comment]
LGTM! 

Verifying root...
	Contains 1/3 valid signatures

Verifying snapshot...
	Contains 0/3 valid signatures

Verifying targets...
	Contains 1/3 valid signatures

Verifying timestamp...
	Contains 0/3 valid signatures

**Comment by hojoungjang** [comment]
```
VERIFIED KEY 13078778

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/13078778/13078778_device_cert.pem) ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem -pubkey -noout

VERIFIED KEY 14454335

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14454335/14454335_device_cert.pem) ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem -pubkey -noout

VERIFIED KEY 14470876

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14470876/14470876_device_cert.pem) ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem -pubkey -noout

VERIFIED KEY 15938765

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938765/15938765_device_cert.pem) ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem -pubkey -noout

VERIFIED KEY 15938791

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938791/15938791_device_cert.pem) ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem -pubkey -noout

Outputting metadata verification...

Verifying root...
        Contains 1/3 valid signatures

Verifying snapshot...
        Contains 0/3 valid signatures

Verifying targets...
        Contains 1/3 valid signatures

Verifying timestamp...
        Contains 0/3 valid signatures
```
LGTM!

**Pull request merged**
