### PR TITLE
Add new root and targets version 2

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

#### Summary
* Adds a newly generated version 2 root and targets. The v2 root should (please verify all of these):
   - Set the 5 original key holders for the root and targets roles with a threshold of 3 and expiration of 4 months
   - Set online keys for snapshot and timestamp roles with a threshold of 1 and expiration of 21 days (3 weeks)
   - Sign off on targets: the new fulcio root, old root (for migration purposes), rekor public key (for migration purposes), the new cosign artifact key, and ctfe key
   - Sign off on new delegations:  
     -  the rekor delegation: which will hold all rekor sharded public keys of the form `rekor.*.pub`. The initial single rekor public key is also stored here as `rekor.0.pub`.
     - the staging projects delegation: empty for now

I nuked the repo created earlier on 10-08, so as such, the diff displayed only shows the mistakes it had! (Incorrect threshold, bad key revocation, a problem with the delegations where delegation keys were overridden every time a new delegation was added).

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by trishankatdatadog** [comment]
`keys not initialized yet`

**Comment by trishankatdatadog** [comment]
The "rekor" delegation _should_ be terminating, because you don't want the conflicting "staging" delegation to provide rekor pubkeys in case they were somehow absent...

**Comment by asraa** [comment]
> keys not initialized yet

I think the repo environment variable isn't set correctly https://github.com/sigstore/root-signing/blob/84f5c47437de2a04df8256b902241a3e976a09fe/scripts/verify.sh#L10

Bob's fixed this in https://github.com/sigstore/root-signing/pull/36 I'll merge

**Review by dlorenc — APPROVED** [review]

**Comment by dlorenc** [comment]
Let's merge!

**Pull request merged**
