### PR TITLE
The lint CI check started timing out. Trying to bump it to 5m.

### PR DESCRIPTION
**Pull request by dlorenc**
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by Hayden-IO** [comment]
15 minutes to run a lint test seems really long - Could this just be a temporary failure?

**Comment by dlorenc** [comment]
Seems like the timeout isn't actually getting passed correctly, it's still failing after 1m:
image

**Comment by asraa** [comment]
We should update the golangci version `golangci-lint-1.39.0`... that might also be a problem

**Comment by dlorenc** [comment]
It looks like the timeout setting there got removed at some point in the action, you now need to pass it in --args.

**Review by asraa — APPROVED** [review]

**Comment by dlorenc** [comment]
It works!

**Pull request merged**
