### PR TITLE
upgrade go to go1.21

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
- upgrade go to go1.21

### CODE REVIEW

**Review by Hayden-IO — DISMISSED** [review]

**Comment by Hayden-IO** [comment]
thank you!

**Comment by bobcallaway** [comment]
should we just be using https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file instead of hard coding this?

**Comment by cpanato** [comment]
> should we just be using https://github.com/actions/setup-go#getting-go-version-from-the-gomod-file instead of hard coding this?

will update, make sense

**Comment by cpanato** [comment]
done @bobcallaway PTAL

**Review by Hayden-IO — APPROVED** [review]

**Review by bobcallaway — APPROVED** [review]

**Pull request merged**
