### PR TITLE
feat/add-delegation for registry.npmjs.org

### PR DESCRIPTION
**Pull request by kommendorkapten**
Testing updated POP verification scripts.

### CODE REVIEW

**Comment by kommendorkapten** [comment]
```shell
$ GITHUB_USER=kommendorkapten ./scripts/dpop-verify.sh 742 registry.npmjs.org
...
+ git checkout VERIFY
Switched to branch 'VERIFY'
++ git rev-parse --abbrev-ref HEAD
+ BRANCH=VERIFY
++ git merge-base origin/main VERIFY
+ FORK_POINT=ffaca56437cc9586550dba5c6b7a6b68f9bf87a2
+ SIG_FILE=./repository/staged/ffaca56437cc9586550dba5c6b7a6b68f9bf87a2.sig
+ '[' '!' -f ./repository/staged/ffaca56437cc9586550dba5c6b7a6b68f9bf87a2.sig ']'
++ cat ./repository/staged/ffaca56437cc9586550dba5c6b7a6b68f9bf87a2.sig
+ SIG=MEUCIQDJrFrDi3JGou0qB7+Qvz2hPpd0tRQ1HcP6nuikCgc/GgIgRXB7VOCAtALqCbAIcV8UJ+ezDDZcX3ou3WnSRRPDapw=
+ ./tuf key-pop-verify -role registry.npmjs.org -challenge registry.npmjs.org -nonce ffaca56437cc9586550dba5c6b7a6b68f9bf87a2 -repository ./repository -sig MEUCIQDJrFrDi3JGou0qB7+Qvz2hPpd0tRQ1HcP6nuikCgc/GgIgRXB7VOCAtALqCbAIcV8UJ+ezDDZcX3ou3WnSRRPDapw=
Verifying using keyid 887361b214fd9c560d88329a8f256314f432000fd4a2bf6b30ac694e3825c678
Signature verified ok
```

**Comment by kommendorkapten** [comment]
The POP workflow verification are erroring out when it tries to add a comment that the signature was successful, I'll look into that.

**Comment by kommendorkapten** [comment]
@asraa when you have time, could you please verify this PR locally?

**Comment by asraa** [comment]
Yes! This is what happened.

I ran

```
./scripts/step-0.sh
./scripts/dpop-verify.sh 742 npmjs.registry.dev [probably misspelled, but figured it should tell me]
```

and the result was:
```
+ git checkout VERIFY
Switched to branch 'VERIFY'
++ git rev-parse --abbrev-ref HEAD
+ BRANCH=VERIFY
++ git merge-base origin/main VERIFY
+ FORK_POINT=e342408c0db1bc9b1702c3443f858aad6bb3420f
+ SIG_FILE=./repository/staged/e342408c0db1bc9b1702c3443f858aad6bb3420f.sig
+ '[' '!' -f ./repository/staged/e342408c0db1bc9b1702c3443f858aad6bb3420f.sig ']'
+ echo Expected signature file: ./repository/staged/e342408c0db1bc9b1702c3443f858aad6bb3420f.sig not found
Expected signature file: ./repository/staged/e342408c0db1bc9b1702c3443f858aad6bb3420f.sig not found
+ exit 1
```

Then I ran `git fetch upstream` and `git rebase upstream/main` to ensure that my main was at the right state.

Then, I realized that my ORIGIN/MAIN was behind, at `e342408c0db1bc9b1702c3443f858aad6bb3420f`.

So I had to run `git push origin main` to ensure my remote origin/main was up to date.

Then I succeeded!

Do we need to get merge-base with a local origin? Or force the local user to push their main to their remote?

**Comment by kommendorkapten** [comment]
Good catch! Now that we don't have the `--fork-point` issue any more, we should be fine to rely on just `main` as merge base, i.e what you propose.

**Review by asraa — APPROVED** [review]
Yes! Now that the fix PR is in for the merge-base, I could verify successfully (and my remote origin/main was not updated to include the fix PR)

```
Switched to branch 'VERIFY'
++ git rev-parse --abbrev-ref HEAD
+ BRANCH=VERIFY
++ git merge-base origin/main VERIFY
+ FORK_POINT=ffaca56437cc9586550dba5c6b7a6b68f9bf87a2
+ SIG_FILE=./repository/staged/ffaca56437cc9586550dba5c6b7a6b68f9bf87a2.sig
+ '[' '!' -f ./repository/staged/ffaca56437cc9586550dba5c6b7a6b68f9bf87a2.sig ']'
++ cat ./repository/staged/ffaca56437cc9586550dba5c6b7a6b68f9bf87a2.sig
+ SIG=MEUCIQDJrFrDi3JGou0qB7+Qvz2hPpd0tRQ1HcP6nuikCgc/GgIgRXB7VOCAtALqCbAIcV8UJ+ezDDZcX3ou3WnSRRPDapw=
+ ./tuf key-pop-verify -role registry.npmjs.org -challenge registry.npmjs.org -nonce ffaca56437cc9586550dba5c6b7a6b68f9bf87a2 -repository ./repository -sig MEUCIQDJrFrDi3JGou0qB7+Qvz2hPpd0tRQ1HcP6nuikCgc/GgIgRXB7VOCAtALqCbAIcV8UJ+ezDDZcX3ou3WnSRRPDapw=
Verifying using keyid 887361b214fd9c560d88329a8f256314f432000fd4a2bf6b30ac694e3825c678
Signature verified ok
```

**Review by asraa — COMMENTED** [review]
I also tried 
```
./scripts/verify.sh
```

to validate the signature:
```
STAGED METADATA

Outputting metadata verification at /home/asraa/git/root-signing/repository...

Verifying registry.npmjs.org.json...
	Contains 0/1 valid signatures from the current staged metadata
	registry.npmjs.org version 1, expires 2023/09/22

Verifying root.json...
	Contains 0/3 valid signatures from the current staged metadata
	Contains 0/3 valid signatures from the previous root
	root version 7, expires 2023/09/22

Verifying targets.json...
	Contains 0/3 valid signatures from the current staged metadata
	targets version 7, expires 2023/09/22
```

Working on this - I have a feeling it's pulling the keys from the previous root metadata

**Comment by kommendorkapten** [comment]
Running a new test ceremony today so closing this.

**Pull request closed without merging**
