### PR TITLE
Setting up root v2

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by dlorenc** [comment]
This LGTM!

**Review by SantiagoTorres — DISMISSED** [review]

**Review by SantiagoTorres — APPROVED** [review]

**Comment by asraa** [comment]
@ethan-lowman-dd @hosseinsia could one of you PTAL? the v1 root is in repository/ and the v2 is in staging/ right now

**Comment by trishankatdatadog** [comment]
```
Outputting key verification and OpenSSL commands...

VERIFIED KEY 13078778

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-08/keys/13078778/13078778_device_cert.pem) ceremony/2021-10-08/keys/13078778/13078778_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-10-08/keys/13078778/13078778_key_cert.pem -pubkey -noout

VERIFIED KEY 14454335

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-08/keys/14454335/14454335_device_cert.pem) ceremony/2021-10-08/keys/14454335/14454335_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-10-08/keys/14454335/14454335_key_cert.pem -pubkey -noout

VERIFIED KEY 14470876

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-08/keys/14470876/14470876_device_cert.pem) ceremony/2021-10-08/keys/14470876/14470876_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-10-08/keys/14470876/14470876_key_cert.pem -pubkey -noout

VERIFIED KEY 15938765

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-08/keys/15938765/15938765_device_cert.pem) ceremony/2021-10-08/keys/15938765/15938765_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-10-08/keys/15938765/15938765_key_cert.pem -pubkey -noout

VERIFIED KEY 15938791

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-08/keys/15938791/15938791_device_cert.pem) ceremony/2021-10-08/keys/15938791/15938791_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-10-08/keys/15938791/15938791_key_cert.pem -pubkey -noout

Outputting metadata verification...

Verifying targets...
	Contains 0/3 valid signatures

Verifying timestamp...
	Success! Signatures valid and threshold achieved

Verifying root...
	Contains 0/3 valid signatures

Verifying snapshot...
	Success! Signatures valid and threshold achieved

Validating completed metadata and retrieving targets...
error initializing client: tuf: failed to decode root.json: tuf: signature verification failed
```

**Comment by asraa** [comment]
Yep -- as expected -- new root and targets are unsigned. the old timestamp and snapshot is still valid.

**Comment by ethan-lowman-dd** [comment]
```
VERIFIED KEY 13078778

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-08/keys/13078778/13078778_device_cert.pem) ceremony/2021-10-08/keys/13078778/13078778_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-10-08/keys/13078778/13078778_key_cert.pem -pubkey -noout

VERIFIED KEY 14454335

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-08/keys/14454335/14454335_device_cert.pem) ceremony/2021-10-08/keys/14454335/14454335_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-10-08/keys/14454335/14454335_key_cert.pem -pubkey -noout

VERIFIED KEY 14470876

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-08/keys/14470876/14470876_device_cert.pem) ceremony/2021-10-08/keys/14470876/14470876_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-10-08/keys/14470876/14470876_key_cert.pem -pubkey -noout

VERIFIED KEY 15938765

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-08/keys/15938765/15938765_device_cert.pem) ceremony/2021-10-08/keys/15938765/15938765_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-10-08/keys/15938765/15938765_key_cert.pem -pubkey -noout

VERIFIED KEY 15938791

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-10-08/keys/15938791/15938791_device_cert.pem) ceremony/2021-10-08/keys/15938791/15938791_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-10-08/keys/15938791/15938791_key_cert.pem -pubkey -noout

Outputting metadata verification...

Verifying root...
        Contains 0/3 valid signatures

Verifying snapshot...
        Success! Signatures valid and threshold achieved

Verifying targets...
        Contains 0/3 valid signatures

Verifying timestamp...
        Success! Signatures valid and threshold achieved

Validating completed metadata and retrieving targets...
error initializing client: tuf: failed to decode root.json: tuf: signature verification failed
```

**Pull request merged**
