### PR TITLE
v3: Update TUF to latest version

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

#### Summary

Now that https://github.com/theupdateframework/go-tuf/pull/175 is merged (YAY!) I'm going to start merging in the v3 changes, starting with a light bump on the TUF version.

Can we open up a separate branch on this repo so we can keep the existing state until all the changes are merged and we can manually test everything? I propose a new branch, something like`v3`

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by asraa** [comment]
Thanks @ethan-lowman-dd, the delegation PR was really critical to getting these next PRs merged!

**Review by Hayden-IO — APPROVED** [review]
Looks good! I assume we've checked that all instances of `data.Key` have been changed?

**Comment by asraa** [comment]
> Looks good! I assume we've checked that all instances of data.Key have been changed?

I've compiled both binaries (which is also in CI), and also manually searched so I think so! Also a good push to have this merge to a separate branch. Mind if I create a `v3-staging` branch @dlorenc ?

**Comment by dlorenc** [comment]
Go for it!

**Comment by asraa** [comment]
Great, changed base!

**Pull request merged**
