### PR TITLE
Adding initial key for SantiagoTorres

### PR DESCRIPTION
**Pull request by SantiagoTorres**
Signed-off-by: Santiago Torres <santiago@archlinux.org>

### CODE REVIEW

**Review by asraa — APPROVED** [review]
LGTM!

VERIFIED KEY 15938765

**Comment by puerco** [comment]
> VERIFIED KEY 15938765
/lgtm

**Comment by znewman01** [comment]
VERIFIED KEY 15938765
LGTM

**Comment by nadgowdas** [comment]
LGTM !

**Comment by ethan-lowman-dd** [comment]
`VERIFIED KEY 15938765`

LGTM

**Comment by garrying** [comment]
LGTM!

**Comment by rszumlakowski** [comment]
LGTM!

**Comment by zjs** [comment]
```
Outputting key verification and OpenSSL commands...

VERIFIED KEY 15938765

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938765/15938765_device_cert.pem) ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem -pubkey -noout
```

```
~/src/root-signing (VERIFY)$ openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938765/15938765_device_cert.pem) ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem
ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem: OK
```

```
~/src/root-signing (VERIFY)$ openssl x509 -in ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem -pubkey -noout
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzBzVOmHCPojMVLSI364WiiV8NPrD
6IgRxVliskz/v+y3JER5mcVGcONliDcWMC5J2lfHmjPNPhb4H7xm8LzfSA==
-----END PUBLIC KEY-----
```

LGTM

**Comment by jchester** [comment]
LGTM

**Comment by denisse-dev** [comment]
LGTM!

VERIFIED KEY 15938765

**Comment by mmalone** [comment]
LGTM

**Comment by hojoungjang** [comment]
LGTM!
`VERIFIED KEY 15938765`
`ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem: OK`
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzBzVOmHCPojMVLSI364WiiV8NPrD
6IgRxVliskz/v+y3JER5mcVGcONliDcWMC5J2lfHmjPNPhb4H7xm8LzfSA==
-----END PUBLIC KEY-----
```

**Comment by tclasen** [comment]
LGTM!

**Pull request merged**
