### PR TITLE
add-key for joshuagl

### PR DESCRIPTION
**Pull request by joshuagl**
Signed-off-by: Joshua Lock <jlock@vmware.com>

### CODE REVIEW

**Review by asraa — APPROVED** [review]
Thank you! LGTM. Added key 18158855
```
$ ./scripts/verify.sh 310

Outputting key verification and OpenSSL commands...

VERIFIED KEY WITH SERIAL NUMBER 18158855
	TUF key id: 75e867ab10e121fdef32094af634707f43ddd79c6bab8ad6c5ab9f03f4ea8c90

# To manually verify the chain for any key ID

	export SERIAL_NUMBER=${SERIAL_NUMBER}
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_device_cert.pem) ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_key_cert.pem

# Manually extract the public key for any key ID and match with published

	export SERIAL_NUMBER=${SERIAL_NUMBER}
	openssl x509 -in ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_pubkey.pem -pubkey -noout
	cat ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_key_cert.pem
```

Verified the chain manually:
```
asraa@asraa1:~/git/root-signing$ export SERIAL_NUMBER=18158855
asraa@asraa1:~/git/root-signing$ openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_device_cert.pem) ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_key_cert.pem
ceremony/2022-07-12/keys/18158855/18158855_key_cert.pem: OK
```

**Comment by bobcallaway** [comment]
```
+ ./verify keys --root piv-attestation-ca.pem --key-directory /Users/bcallaway/git/sigstore/root-signing/ceremony/2022-07-12/keys

Outputting key verification and OpenSSL commands...

VERIFIED KEY WITH SERIAL NUMBER 18158855
	TUF key id: 75e867ab10e121fdef32094af634707f43ddd79c6bab8ad6c5ab9f03f4ea8c90
```

**Comment by endorama** [comment]
```
VERIFIED KEY WITH SERIAL NUMBER 18158855
	TUF key id: 75e867ab10e121fdef32094af634707f43ddd79c6bab8ad6c5ab9f03f4ea8c90

~/code/github.com/sigstore/root-signing$ export SERIAL_NUMBER=18158855
~/code/github.com/sigstore/root-signing$ openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_device_cert.pem) ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_key_cert.pem
ceremony/2022-07-12/keys/18158855/18158855_key_cert.pem: OK
```

**Comment by asraa** [comment]
thanks everyone! will merge with one more positive review :) community members chime in!

**Comment by Hayden-IO** [comment]
```
$ ./scripts/verify.sh 310

Outputting key verification and OpenSSL commands...

VERIFIED KEY WITH SERIAL NUMBER 18158855
	TUF key id: 75e867ab10e121fdef32094af634707f43ddd79c6bab8ad6c5ab9f03f4ea8c90

# To manually verify the chain for any key ID

	export SERIAL_NUMBER=${SERIAL_NUMBER}
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_device_cert.pem) ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_key_cert.pem

# Manually extract the public key for any key ID and match with published

	export SERIAL_NUMBER=${SERIAL_NUMBER}
	openssl x509 -in ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_key_cert.pem -pubkey -noout
	cat ceremony/2022-07-12/keys/${SERIAL_NUMBER}/${SERIAL_NUMBER}_pubkey.pem
```

**Pull request merged**
