### PR TITLE
Adding initial key for dlorenc

### PR DESCRIPTION
**Pull request by dlorenc**
Signed-off-by: Dan Lorenc <dlorenc@google.com>

### CODE REVIEW

**Review by asraa — APPROVED** [review]
LGTM!

**Comment by tiziano88** [comment]
where are the snacks?

**Comment by denisse-dev** [comment]
LGTM!

VERIFIED KEY 13078778

# Manually verify the chain
ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem: OK

# Manually extract the public key
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEy8XKsmhBYDI8Jc0GwzBxeKax0cm5
STKEU65HPFunUn41sT8pi0FjM4IkHz/YUmwmLUO0Wt7lxhj6BkLIK4qYAw==
-----END PUBLIC KEY-----

**Comment by puerco** [comment]
```
Outputting key verification and OpenSSL commands...

VERIFIED KEY 13078778
```
/lgtm

**Comment by garrying** [comment]
LGTM!

**Comment by znewman01** [comment]
LGTM

**Comment by zjs** [comment]
```Outputting key verification and OpenSSL commands...

VERIFIED KEY 13078778

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/13078778/13078778_device_cert.pem) ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem -pubkey -noout
```

```
~/src/root-signing (VERIFY)$ openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/13078778/13078778_device_cert.pem) ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem
ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem: OK
```

```
~/src/root-signing (VERIFY)$ openssl x509 -in ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem -pubkey -noout
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEy8XKsmhBYDI8Jc0GwzBxeKax0cm5
STKEU65HPFunUn41sT8pi0FjM4IkHz/YUmwmLUO0Wt7lxhj6BkLIK4qYAw==
-----END PUBLIC KEY-----
```

LGTM

**Comment by mmalone** [comment]
LGTM

**Comment by ethan-lowman-dd** [comment]
`VERIFIED KEY 13078778`

LGTM

**Comment by gkovan** [comment]
LGTM

**Comment by rszumlakowski** [comment]
What's with all the pineapple pizza hate?

**Comment by nishakm** [comment]
LGTM

**Comment by xopham** [comment]
LGTM :muscle:

**Comment by linusbrogan** [comment]
LGTM

`VERIFIED KEY 13078778`

```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEy8XKsmhBYDI8Jc0GwzBxeKax0cm5
STKEU65HPFunUn41sT8pi0FjM4IkHz/YUmwmLUO0Wt7lxhj6BkLIK4qYAw==
-----END PUBLIC KEY-----
```

**Comment by hojoungjang** [comment]
A little late but LGTM!
`VERIFIED KEY 13078778`
`ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem: OK`
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEy8XKsmhBYDI8Jc0GwzBxeKax0cm5
STKEU65HPFunUn41sT8pi0FjM4IkHz/YUmwmLUO0Wt7lxhj6BkLIK4qYAw==
-----END PUBLIC KEY-----
```

**Comment by asraa** [comment]
Thanks @hojoung97 ! It will always be here for posterity!

**Comment by tclasen** [comment]
LGTM!

**Pull request merged**
