### PR TITLE
Adding initial key for bobcallaway

### PR DESCRIPTION
**Pull request by bobcallaway**
Signed-off-by: Bob Callaway <bob.callaway@gmail.com>

### CODE REVIEW

**Review by asraa — APPROVED** [review]
LGTM!

VERIFIED KEY 15938791

**Comment by puerco** [comment]
VERIFIED KEY 15938791
/lgtm

**Comment by znewman01** [comment]
LGTM
VERIFIED KEY 15938791

**Comment by ethan-lowman-dd** [comment]
`VERIFIED KEY 15938791`

LGTM

**Comment by zjs** [comment]
```
Outputting key verification and OpenSSL commands...

VERIFIED KEY 15938791

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938791/15938791_device_cert.pem) ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem -pubkey -noout
```

```
~/src/root-signing (VERIFY)$ openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938791/15938791_device_cert.pem) ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem
ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem: OK
```

```
~/src/root-signing (VERIFY)$ openssl x509 -in ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem -pubkey -noout
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEinikSsAQmYkNeH5eYq/CnIzLaacO
xlSaawQDOwqKy/tCqxq5xxPSJc21K4WIhs9GyOkKfzueY3GILzcMJZ4cWw==
-----END PUBLIC KEY-----
```

LGTM

**Comment by rszumlakowski** [comment]
Go go go!

**Comment by magnologan** [comment]
VERIFIED KEY 15938791
/lgtm

**Comment by mmalone** [comment]
LGTM

**Comment by garrying** [comment]
LGTM!!

**Comment by jchester** [comment]
LGTM

**Comment by nishakm** [comment]
LGTM

**Comment by hojoungjang** [comment]
A little late but LGTM!
`VERIFIED KEY 15938791`
`ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem: OK`
```
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEinikSsAQmYkNeH5eYq/CnIzLaacO
xlSaawQDOwqKy/tCqxq5xxPSJc21K4WIhs9GyOkKfzueY3GILzcMJZ4cWw==
-----END PUBLIC KEY-----
```

**Comment by tclasen** [comment]
LGTM!

**Pull request merged**
