### PR TITLE
Disable caching on the TUF root objects.

### PR DESCRIPTION
**Pull request by dlorenc**
Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by dlorenc** [comment]
I think this should fix #166

**Review by Hayden-IO — APPROVED** [review]

**Comment by Hayden-IO** [comment]
Did you manually set it on the objects? I see it's off for all metadata in the GCP UI.

Is this recursive? Does it also disable caching on the target files?

**Comment by Hayden-IO** [comment]
Unclear from the [docs](https://cloud.google.com/sdk/gcloud/reference/alpha/storage/cp#--cache-control), but I'll assume that `-r` applies it recursively.

**Comment by dlorenc** [comment]
Yeah - I tried this manually first to make sure gcloud alpha storage will work.

**Pull request merged**
