### PR TITLE
'registry.npmjs.org' role/delegation change

### PR DESCRIPTION
**Pull request by kommendorkapten**
This is my signing event contribution.

CC @sigstore/tuf-root-signing-codeowners, please have a look
and merge into the signing event branch.

Closes https://github.com/sigstore/root-signing/issues/1330

### CODE REVIEW

**Comment by jku** [comment]
Right, so situation is:
* we were hoping to avoid artifact updates because the hash choice then changes (from both sha512,sha256 to just sha256)
* this makes an artifact change on the delegation but that leads to the artifact update in top level targets as well...


I suppose our choices are 
1. just merge this and take the artifact update -- this does mean sigstore clients would see the hash choice change that we've only tested in staging for 4 days now...
2. manually remove the artifact changes  from the top level targets here -- I don't like it but it should work. npmjs delegation will still have the artifact change but normal sigstore clients won't care about that

**Comment by jku** [comment]
would have been great to test all this out in staging

**Comment by kommendorkapten** [comment]
I'll open a similar PR on staging, and sign it too.

**Comment by jku** [comment]
> this makes an artifact change on the delegation 

that was me misunderstanding what's being done (more explanations would be useful).

In reality there is no artifact change. The bot commits here were done in frederiks own fork (where the bot was likely confused since the main branch had old artifacts)

**Review by jku — APPROVED** [review]
I think this looks good

**Comment by kommendorkapten** [comment]
This PR is now ready for review. As per #1330 it introduces the new key for the `registry.npmjs.org` delegation. No version bump is required as that is already performed in the `sign/migration` branch.

**Pull request merged**
