### PR TITLE
Signing snapshot for dlorenc

### PR DESCRIPTION
**Pull request by dlorenc**
Signed-off-by: Dan Lorenc <dlorenc@google.com>

### CODE REVIEW

**Comment by zjs** [comment]
```
Outputting key verification and OpenSSL commands...

VERIFIED KEY 13078778

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/13078778/13078778_device_cert.pem) ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem -pubkey -noout

VERIFIED KEY 14454335

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14454335/14454335_device_cert.pem) ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem -pubkey -noout

VERIFIED KEY 14470876

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14470876/14470876_device_cert.pem) ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem -pubkey -noout

VERIFIED KEY 15938765

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938765/15938765_device_cert.pem) ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem -pubkey -noout

VERIFIED KEY 15938791

	# Manually verify the chain
	openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938791/15938791_device_cert.pem) ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem

	# Manually extract the public key
	openssl x509 -in ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem -pubkey -noout

Outputting metadata verification...

Verifying root...
	Success! Signatures valid and threshold achieved

Verifying snapshot...
	Contains 1/3 valid signatures

Verifying targets...
	Success! Signatures valid and threshold achieved

Verifying timestamp...
	Contains 0/3 valid signatures
```

LGTM

**Comment by linusbrogan** [comment]
LGTM

```
Outputting key verification and OpenSSL commands...

VERIFIED KEY 13078778

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/13078778/13078778_device_cert.pem) ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-06-18/keys/13078778/13078778_key_cert.pem -pubkey -noout

VERIFIED KEY 14454335

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14454335/14454335_device_cert.pem) ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-06-18/keys/14454335/14454335_key_cert.pem -pubkey -noout

VERIFIED KEY 14470876

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/14470876/14470876_device_cert.pem) ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-06-18/keys/14470876/14470876_key_cert.pem -pubkey -noout

VERIFIED KEY 15938765

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938765/15938765_device_cert.pem) ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-06-18/keys/15938765/15938765_key_cert.pem -pubkey -noout

VERIFIED KEY 15938791

        # Manually verify the chain
        openssl verify -verbose -x509_strict -CAfile <(cat piv-attestation-ca.pem ceremony/2021-06-18/keys/15938791/15938791_device_cert.pem) ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem

        # Manually extract the public key
        openssl x509 -in ceremony/2021-06-18/keys/15938791/15938791_key_cert.pem -pubkey -noout

Outputting metadata verification...

Verifying root...
        Success! Signatures valid and threshold achieved

Verifying snapshot...
        Contains 1/3 valid signatures

Verifying targets...
        Success! Signatures valid and threshold achieved

Verifying timestamp...
        Contains 0/3 valid signatures
```

**Review by asraa — APPROVED** [review]
Verifying root...
	Success! Signatures valid and threshold achieved

Verifying snapshot...
	Contains 1/3 valid signatures

Verifying targets...
	Success! Signatures valid and threshold achieved

Verifying timestamp...
	Contains 0/3 valid signatures

LGTM!

**Comment by jchester** [comment]
```
$ pbpaste | shasum -a 512
87d41965ac08a2e03a33aa2db1dbbf5a7d6616e49f0ca3b20afe1c46ae78e52e841e21cca347f7b77ec929b6a3687d86d320ee04ba5f75a1880974310958b9c2  -
```

`root.json` LGTM.

**Comment by hojoungjang** [comment]
```
Verifying targets...
        Success! Signatures valid and threshold achieved

Verifying timestamp...
        Contains 0/3 valid signatures

Verifying root...
        Success! Signatures valid and threshold achieved

Verifying snapshot...
        Contains 1/3 valid signatures
```
LGTM!

**Pull request merged**
