### PR TITLE
Setting up new root 2021-11-11

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

#### Summary

* Removes the october root tryout and creates the new root that picks up the signing changes for the rust tuf compatibility
* Stuff to double check 
   - the new fulcio cert removes the whitespace
   - the rekor delegation is terminating
   - we include sha256's for all the file meta for rust TUF
  

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Review by trishankatdatadog — COMMENTED** [review]
Interesting, thanks!

Seems like there is no reconciliation yet between staged and production targets, no? In particular, see the Fulcio PEM cert.

**Comment by asraa** [comment]
> Seems like there is no reconciliation yet between staged and production targets, no? In particular, see the Fulcio PEM cert.

Yeah, the `repository/targets/fulcio.crt.pem` is the v1 whitespace version. The `staged/targets/fulcio.crt.pem` is the v2 fixed version. It'll only get replaced once the repo is published/committed!

**Comment by trishankatdatadog** [comment]
This is so exciting!

**Comment by asraa** [comment]
Could I please get one more LGTM from a keyholder?
@dlorenc @lukehinds @bobcallaway @mnm678 @SantiagoTorres

**Review by bobcallaway — APPROVED** [review]
lgtm

**Pull request merged**
