### PR TITLE
fix: remove staged subfolder

### PR DESCRIPTION
**Pull request by asraa**
* Manually removes the staged/ subfolder of the repository.

This is an artifact of the workflow, see https://github.com/sigstore/root-signing/issues/782 for details. It does not affect pre-prod or prod bucket states.

### CODE REVIEW

**Review by Hayden-IO — APPROVED** [review]
Oh just posted about this!

**Comment by Hayden-IO** [comment]
What about the POP? As in, is this in any other place?

**Comment by asraa** [comment]
Not in any other place, but the POP has already been removed from the repository subfolder.
https://github.com/sigstore/root-signing/pull/776

**Comment by Hayden-IO** [comment]
Just wanted to check removing it here is intentional! So we will recreate the POP later on and store it elsewhere I assume?

**Comment by asraa** [comment]
> Just wanted to check removing it here is intentional! So we will recreate the POP later on and store it elsewhere I assume?

Hmmmmmmmm... I'm not sure I totally understand - the POP was already verified when the delegation was merged as a PR into this repository - it doesn't belong in the TUF repo itself. The history of it is in the PRs though.

**Comment by asraa** [comment]
You may want to comment on this: https://github.com/sigstore/root-signing/issues/775

If we solve it with option (2) from that, then it can stay in a subfolder "delegation_pops" adjacent to the TUF repo, like we do with `keys` holding the HSM cert info.

**Comment by Hayden-IO** [comment]
Ah, I was thinking the POP would be checked periodically so it'd need to be persisted.

**Pull request merged**
