### PR TITLE
Change to maintained crate installer, cache binary

### LINKED ISSUE #924: Improve tuftool install time
**Description**

tuftool takes very long to install, causing https://github.com/sigstore/root-signing/blob/main/.github/workflows/tuf_client_tests.yml to take ~10 minutes to run.

@woodruffw, did you have any suggestions on how to improve rust app install time? I know we ran into this in protobuf-specs too.

### PR DESCRIPTION
**Pull request by Hayden-IO**
This should improve runtime of TUF client tests.

Fixes https://github.com/sigstore/root-signing/issues/924

### CODE REVIEW

**Comment by Hayden-IO** [comment]
`actions-rs/install` is no longer maintained and the caching mechanism is broken.

**Review by woodruffw — APPROVED** [review]
LGTM!

This replacement action looks fine to me, but in case you're wary of a 3p dep: it would probably be easy to get the equivalent caching here with `actions/cache@v3` and a normal `cargo install` invocation. I'd be happy to quickly do that, if you'd like.

**Comment by Hayden-IO** [comment]
Sure if you'd like to!

**Review by hectorj2f — APPROVED** [review]

**Review by cpanato — APPROVED** [review]

**Review by kommendorkapten — APPROVED** [review]

**Comment by woodruffw** [comment]
> Sure if you'd like to!

Cool, I'll make a PR today or tomorrow. In the mean time I think merging this makes sense!

**Review by woodruffw — APPROVED** [review]

**Pull request merged**
