### PR TITLE
docs: add link to ceremony video on twitch.tv

### PR DESCRIPTION
**Pull request by wilsonmar**

### CODE REVIEW

**Comment by wilsonmar** [comment]
Don't I need to make signed commit for this?

**Comment by cpanato** [comment]
@wilsonmar you need to sign the commit, can you do that?
```
git commit --amend --no-edit --signoff
```

**Review by trishankatdatadog — APPROVED** [review]

**Comment by Hayden-IO** [comment]
There's no content up at https://www.twitch.tv/videos/1060206516 for me.

**Comment by Hayden-IO** [comment]
@dlorenc @asraa Do either of y'all have the ceremony recorded? Otherwise, we should probably close this. We also didn't record the v3 signing - did we want to record v4?

**Comment by dlorenc** [comment]
https://www.youtube.com/watch?v=GEuFsc8Zm9U

**Comment by trishankatdatadog** [comment]
> https://www.youtube.com/watch?v=GEuFsc8Zm9U

Look at that handsome guy in the end

**Comment by Hayden-IO** [comment]
Closing, made a new PR with the youtube link

**Pull request closed without merging**
