### PR TITLE
Upload TUF metadata in reverse read order to avoid errors

### PR DESCRIPTION
**Pull request by Hayden-IO**
If a timestamp is downloaded before a snapshot is uploaded
for example, then there will be a msimatch in metadata. Once
consistent snapshots are enabled, in combination with this PR,
then a mismatch will not occur, since the last file to be uploaded
will be a timestamp, which will reference a versioned snapshot
(which will then reference versioned targets).

More details in #171.

Signed-off-by: Hayden Blauzvern <hblauzvern@google.com>

#### Ticket Link

Fixes

#### Release Note

```release-note

```

### CODE REVIEW

**Comment by Hayden-IO** [comment]
cc @znewman01

**Review by znewman01 — DISMISSED** [review]
Thanks! 👍 

I have a slight worry about somehow missing a file if we add more delegations. How confident are we that we would notice that before it became a problem?

Otherwise LGTM

**Comment by Hayden-IO** [comment]
I think this can be part of a playbook for delegations - Alternatively, we could move delegate metadata into a single folder.

**Comment by asraa** [comment]
> I have a slight worry about somehow missing a file if we add more delegations. How confident are we that we would notice that before it became a problem?

We could do some bash scripting to take out all the top-level files from the list of files in the directory :P


> Alternatively, we could move delegate metadata into a single folder.

That might mess with TUF client discovery, since per spec the files need to be relative to the root. (Right now you can use the repository subfolder as a local TUF repository, and I wouldn't want to make too many changes where someone can't just spin that up in a single line)

**Comment by Hayden-IO** [comment]
Yea, I had wrote up a bash script for this too.. lemme push that up.

**Comment by dlorenc** [comment]
Nice fix!

**Comment by Hayden-IO** [comment]
Changed it to a simple bash script - As Zach noted in the issue, only the timestamp needs to be committed last, the others can be in any order.

Confirmed this works:

```
$ for f in $(ls repository/repository/ -I *timestamp.json)
> do
> gcloud alpha --quiet storage cp --cache-control=no-store -r repository/repository/$f gs://hbl1234-us-west1-test
> done
Copying file://repository/repository/1.root.json to gs://hbl1234-us-west1-test/1.root.json
  Completed files 1/1 | 5.0kiB/5.0kiB
Copying file://repository/repository/2.root.json to gs://hbl1234-us-west1-test/2.root.json
  Completed files 1/1 | 5.2kiB/5.2kiB
Copying file://repository/repository/rekor.json to gs://hbl1234-us-west1-test/rekor.json
  Completed files 1/1 | 697.0B/697.0B
Copying file://repository/repository/root.json to gs://hbl1234-us-west1-test/root.json
  Completed files 1/1 | 5.2kiB/5.2kiB
Copying file://repository/repository/snapshot.json to gs://hbl1234-us-west1-test/snapshot.json
  Completed files 1/1 | 1.6kiB/1.6kiB
Copying file://repository/repository/staging.json to gs://hbl1234-us-west1-test/staging.json
  Completed files 1/1 | 401.0B/401.0B
Copying file://repository/repository/targets/rekor.0.pub to gs://hbl1234-us-west1-test/targets/rekor.0.pub
Copying file://repository/repository/targets/rekor.pub to gs://hbl1234-us-west1-test/targets/rekor.pub
Copying file://repository/repository/targets/ctfe.pub to gs://hbl1234-us-west1-test/targets/ctfe.pub
Copying file://repository/repository/targets/artifact.pub to gs://hbl1234-us-west1-test/targets/artifact.pub
Copying file://repository/repository/targets/fulcio_v1.crt.pem to gs://hbl1234-us-west1-test/targets/fulcio_v1.crt.pem
Copying file://repository/repository/targets/fulcio.crt.pem to gs://hbl1234-us-west1-test/targets/fulcio.crt.pem
  Completed files 6/6 | 2.1kiB/2.1kiB

Average throughput: 30.3kiB/s
Copying file://repository/repository/targets.json to gs://hbl1234-us-west1-test/targets.json
  Completed files 1/1 | 4.1kiB/4.1kiB
```

**Review by dlorenc — APPROVED** [review]

**Pull request merged**
